#ifndef TEMPERATURES_H
#define TEMPERATURES_H

enum TemperaturesReturnCode {
    TEMPERATURES_RC_OK,
    TEMPERATURES_RC_ERROR,
};

enum TemperaturesName {
    TEMPERATURES_NAME_INVERTER1,
    TEMPERATURES_NAME_INVERTER2,
    TEMPERATURES_NAME_INVERTER3,
    TEMPERATURES_NAME_INVERTER4,
    TEMPERATURES_NAME_MOTOR1,
    TEMPERATURES_NAME_MOTOR2,
    TEMPERATURES_NAME_MOTOR3,
    TEMPERATURES_NAME_MOTOR4,
    TEMPERATURES_NAME_COUNT,
};

struct TemperaturesHandler {
    float temperatures[TEMPERATURES_NAME_COUNT];
};

#endif // TEMPERATURES_H
