[platformio]
src_dir = Core/Src
include_dir = Core/Inc
test_dir = Core/Test
default_envs = nucleo_f767zi

[env]
lib_deps =
    https://github.com/eagletrt/libeagletrt-sw.git#v0.1.0

build_flags =
    -ICore/Inc
    -ICore/Inc/ecu/fsm
    -ICore/Inc/ecu/buzzer
    -ICore/Inc/ecu/pedals
    -ICore/Inc/ecu/tractive-system

[env:native]
platform = native
test_framework = unity
test_build_src = true

lib_deps =
    ${env.lib_deps}
    throwtheswitch/Unity@^2.6.0

build_flags =
    ${env.build_flags}
    -ICore/Test/include
    -DEAGLETRT_STATIC= ;into nothing, making the variable global

build_src_filter = 
    +<ecu/fsm/ecu_fsm.c>
    +<ecu/buzzer/buzzer-api.c>
    +<ecu/pedals/pedals-api.c>
    +<ecu/tractive-system/tractive-system-api.c>

check_tool = clangtidy
check_flags =
    clangtidy: --checks=-*,cert-*,clang-analyzer-*,bugprone-*,performance-*,readability-*
    clangtidy: --warnings-as-errors=clang-analyzer-*,bugprone-*
    clangtidy: --header-filter=^.*Core/(Inc|Src)/.*
    clangtidy: --system-headers=false
check_src_filters = 
    -<**>
    +<Core/Src/*>
    +<Core/Inc/*> 
    +<Core/Test/*> 

[env:nucleo_f767zi]
platform = ststm32
board = nucleo_f767zi
upload_protocol = stlink
debug_tool = stlink
monitor_speed = 115200
board_build.ldscript = stm32f767vgtx_flash.ld

build_flags =
    ${env.build_flags}
    -Wall
    -Wextra
    -Wpedantic
    -IDrivers/CMSIS/Include
    -IDrivers/STM32F7xx_HAL_Driver/Inc
    -IDrivers/STM32F7xx_HAL_Driver/Inc/Legacy
    -IDrivers/CMSIS/Device/ST/STM32F7xx/Include
    -DUSE_HAL_DRIVER

check_src_filters =
    +<Core/Src/*>
    +<Core/Inc/*>
    +<Core/Test/*>
    -<Drivers/*>