[platformio]
src_dir = Core/Src
include_dir = Core/Inc
test_dir = Core/Test

default_envs= nucleo_f767zi ;pio run will exclude native env

[env]
lib_deps = https://github.com/eagletrt/libeagletrt-sw.git#v0.1.0

;to run tests simply run pio test -e native
[env:native]
platform = native
test_framework = unity
test_build_src = true
lib_deps = 
    throwtheswitch/Unity@^2.6.0
    https://github.com/eagletrt/libeagletrt-sw.git#v0.1.0

build_flags =
    -ICore/Test/include
    -ICore/Inc/ecu
    -ICore/Inc/buzzer
    -ICore/Inc/pedals
    -ICore/Inc/tractive-system

build_src_filter = 
    +<ecu/ecu_fsm.c>
    +<buzzer/buzzer-api.c>
    +<pedals/pedals-api.c>
    +<tractive-system/tractive-system-api.c>

[env:nucleo_f767zi]
platform = ststm32
board = nucleo_f767zi
upload_protocol = stlink
debug_tool = stlink
monitor_speed = 115200
board_build.ldscript = stm32f767vgtx_flash.ld

check_src_filters =
    +<Core/Src/*>
    +<Core/Inc/*>
    +<Core/Test/*>
    -<Drivers/*>

build_flags = 
    -Wall
    -Wextra
    -Wpedantic 
    -ICore/Inc/ecu
    -ICore/Inc/buzzer
    -ICore/Inc/pedals
    -ICore/Inc/tractive-system
	-ICore/Inc
    -IDrivers/CMSIS/Include
    -IDrivers/STM32F7xx_HAL_Driver/Inc
    -IDrivers/STM32F7xx_HAL_Driver/Inc/Legacy
    -IDrivers/CMSIS/Device/ST/STM32F7xx/Include
    -DUSE_HAL_DRIVER

build_src_filter = 
