/*!
 * \file can-communication-api.h
 * \author Dorijan Di Zepp
 * \date 2026-06-13
 * \brief Generic API interface for routing serialized CAN buffers via PAL.
 */

#ifndef CAN_COMMUNICATION_API_H
#define CAN_COMMUNICATION_API_H

#include "can-communication.h"

/*!
 * \brief Initializes the CAN communication module by binding the 3 physical PAL interfaces.
 * \param[in] can1 Pointer to the PAL handler instance for the CAN 1 peripheral.
 * \param[in] can2 Pointer to the PAL handler instance for the CAN 2 peripheral.
 * \param[in] can3 Pointer to the PAL handler instance for the CAN 3 peripheral.
 * \retval CAN_COMM_RC_OK if the context initialization completes successfully.
 * \retval CAN_COMM_RC_NULL_POINTER if any of the provided PAL handlers are NULL.
 */
enum CanCommunicationReturnCode can_communication_api_init(struct PalHandler *can1,
                                                           struct PalHandler *can2,
                                                           struct PalHandler *can3);

/*!
 * \brief Pushes a raw, serialized buffer received from a CAN interrupt into the PAL RX queue.
 * \note Call this directly inside your low-level hardware ISR callbacks.
 * \param[in] node The physical CAN network node where the message arrived.
 * \param[in] buffer Pointer to the raw byte sequence generated by the hardware interface.
 * \param[in] length Total size of the received byte sequence.
 * \retval CAN_COMM_RC_OK if the buffer was safely queued into PAL.
 * \retval CAN_COMM_RC_INVALID_ARGUMENT if the targeted node is out of bounds.
 * \retval CAN_COMM_RC_BUFFER_FULL if the underlying PAL RX buffer is completely full.
 */
enum CanCommunicationReturnCode can_communication_api_add_to_rx(enum CanCommunicationNode node,
                                                                const uint8_t *buffer,
                                                                uint32_t length);

/*!
 * \brief Processes and drains the incoming RX queues for all active CAN nodes.
 *
 * \details This function iterates sequentially through all configured CAN communication nodes, 
 * popping raw pending data frames from their respective PAL ring buffers. It triggers 
 * the internal PAL message extraction and automatically fires the deserialization callback 
 * registered during initialization.
 *
 * The provided \p application_state pointer is forwarded completely unmodified through 
 * the PAL translation layer directly into the callback execution context.
 *
 * \param[in,out] application_state Generic pointer to the destination target structure 
 * (e.g. vehicle status tracker) where the deserialized metrics will be stored by the callback.
 *
 * \retval CAN_COMM_RC_OK           If all queues were processed cleanly until exhaustion.
 * \retval CAN_COMM_RC_NULL_POINTER If the underlying hardware abstraction layer bindings evaluate to NULL.
 * \retval CAN_COMM_RC_ERROR        If a low-level driver or interface exception bubbles up from the PAL processing core.
 */
enum CanCommunicationReturnCode can_communication_api_process_rx(void *application_state);

/*!
 * \brief Stages an already serialized message buffer into a specific node's PAL TX queue.
 * \details The application layer runs `canlib` first to get a raw payload buffer, 
 * then passes that buffer here to prepare it for physical transmission.
 * \param[in] node The target physical CAN network node for transmission.
 * \param[in] buffer Pointer to the serialized byte array provided by the upper layers/canlib.
 * \param[in] length Total size of the serialized byte array.
 * \retval CAN_COMM_RC_OK if the buffer was successfully staged into the PAL queue.
 * \retval CAN_COMM_RC_INVALID_ARGUMENT if parameters exceed standard node limits.
 * \retval CAN_COMM_RC_BUFFER_FULL if the targeted PAL network segment queue is saturated.
 */
enum CanCommunicationReturnCode can_communication_api_add_to_tx(enum CanCommunicationNode node,
                                                                const uint8_t *buffer,
                                                                uint32_t length);

/*!
 * \brief Commits and flushes all staged buffers out to the 3 physical CAN hardware lines.
 * \details Executed at the very end of an FSM loop iteration to execute the actual 
 * transmission of all queued messages simultaneously.
 * \retval CAN_COMM_RC_OK if all staged buffers were successfully passed to the hardware layer.
 * \retval CAN_COMM_RC_TRANSMISSION_ERROR if downstream hardware encounters an IO or bus failure.
 */
enum CanCommunicationReturnCode can_communication_api_process_tx(void);

#endif