/******************************************************************************
Finite State Machine
Project: ecu_fsm.dot
Description: ecu_fsm

Generated by gv_fsm ruby gem, see https://rubygems.org/gems/gv_fsm
gv_fsm version 0.5.2
Generation date: 2025-09-20 16:40:57 +0200
Generated from: ecu_fsm.dot
The finite state machine has:
  20 states
  0 transition functions

******************************************************************************/

#include "ecu_fsm.h"

// SEARCH FOR Your Code Here FOR CODE INSERTION POINTS!

// GLOBALS
// State human-readable names
const char *state_names[] = {"init", "enable_inv_updates", "check_inv_settings", "idle", "fatal_error", "start_ts_precharge", "shutdown", "as_init_error", "wait_driver", "wait_ts_precharge", "precharge_error", "start_ts_discharge", "enable_as_driver", "enable_inv_drive", "check_as_settings", "disable_as_driver", "drive", "disable_inv_drive", "re_enable_inv_drive", "wait_ts_discharge"};

// List of state functions
state_func_t *const state_table[NUM_STATES] = {
  do_init,                // in state init
  do_enable_inv_updates,  // in state enable_inv_updates
  do_check_inv_settings,  // in state check_inv_settings
  do_idle,                // in state idle
  do_fatal_error,         // in state fatal_error
  do_start_ts_precharge,  // in state start_ts_precharge
  do_shutdown,            // in state shutdown
  do_as_init_error,       // in state as_init_error
  do_wait_driver,         // in state wait_driver
  do_wait_ts_precharge,   // in state wait_ts_precharge
  do_precharge_error,     // in state precharge_error
  do_start_ts_discharge,  // in state start_ts_discharge
  do_enable_as_driver,    // in state enable_as_driver
  do_enable_inv_drive,    // in state enable_inv_drive
  do_check_as_settings,   // in state check_as_settings
  do_disable_as_driver,   // in state disable_as_driver
  do_drive,               // in state drive
  do_disable_inv_drive,   // in state disable_inv_drive
  do_re_enable_inv_drive, // in state re_enable_inv_drive
  do_wait_ts_discharge,   // in state wait_ts_discharge
};
// No transition functions

/*  ____  _        _       
 * / ___|| |_ __ _| |_ ___ 
 * \___ \| __/ _` | __/ _ \
 *  ___) | || (_| | ||  __/
 * |____/ \__\__,_|\__\___|
 *                         
 *   __                  _   _                 
 *  / _|_   _ _ __   ___| |_(_) ___  _ __  ___ 
 * | |_| | | | '_ \ / __| __| |/ _ \| '_ \/ __|
 * |  _| |_| | | | | (__| |_| | (_) | | | \__ \
 * |_|  \__,_|_| |_|\___|\__|_|\___/|_| |_|___/
 */                                             

// Function to be executed in state init
// valid return states: STATE_ENABLE_INV_UPDATES
state_t do_init(state_data_t *data) {
  state_t next_state = STATE_ENABLE_INV_UPDATES;
  /* Your Code Here */
  
  switch (next_state) {
  case STATE_ENABLE_INV_UPDATES:
    break;
  default:
    next_state = NO_CHANGE;
  }

  return next_state;
}


// Function to be executed in state enable_inv_updates
// valid return states: NO_CHANGE, STATE_ENABLE_INV_UPDATES, STATE_CHECK_INV_SETTINGS
state_t do_enable_inv_updates(state_data_t *data) {
  state_t next_state = NO_CHANGE;
  /* Your Code Here */
  
  switch (next_state) {
  case NO_CHANGE:
  case STATE_ENABLE_INV_UPDATES:
  case STATE_CHECK_INV_SETTINGS:
    break;
  default:
    next_state = NO_CHANGE;
  }

  return next_state;
}


// Function to be executed in state check_inv_settings
// valid return states: NO_CHANGE, STATE_CHECK_INV_SETTINGS, STATE_IDLE, STATE_FATAL_ERROR
state_t do_check_inv_settings(state_data_t *data) {
  state_t next_state = NO_CHANGE;
  /* Your Code Here */
  
  switch (next_state) {
  case NO_CHANGE:
  case STATE_CHECK_INV_SETTINGS:
  case STATE_IDLE:
  case STATE_FATAL_ERROR:
    break;
  default:
    next_state = NO_CHANGE;
  }

  return next_state;
}


// Function to be executed in state idle
// valid return states: NO_CHANGE, STATE_IDLE, STATE_FATAL_ERROR, STATE_START_TS_PRECHARGE, STATE_SHUTDOWN
state_t do_idle(state_data_t *data) {
  state_t next_state = NO_CHANGE;
  /* Your Code Here */
  
  switch (next_state) {
  case NO_CHANGE:
  case STATE_IDLE:
  case STATE_FATAL_ERROR:
  case STATE_START_TS_PRECHARGE:
  case STATE_SHUTDOWN:
    break;
  default:
    next_state = NO_CHANGE;
  }

  return next_state;
}


// Function to be executed in state fatal_error
// valid return states: NO_CHANGE, STATE_FATAL_ERROR, STATE_SHUTDOWN
state_t do_fatal_error(state_data_t *data) {
  state_t next_state = NO_CHANGE;
  /* Your Code Here */
  
  switch (next_state) {
  case NO_CHANGE:
  case STATE_FATAL_ERROR:
  case STATE_SHUTDOWN:
    break;
  default:
    next_state = NO_CHANGE;
  }

  return next_state;
}


// Function to be executed in state start_ts_precharge
// valid return states: NO_CHANGE, STATE_START_TS_PRECHARGE, STATE_WAIT_TS_PRECHARGE, STATE_PRECHARGE_ERROR
state_t do_start_ts_precharge(state_data_t *data) {
  state_t next_state = NO_CHANGE;
  /* Your Code Here */
  
  switch (next_state) {
  case NO_CHANGE:
  case STATE_START_TS_PRECHARGE:
  case STATE_WAIT_TS_PRECHARGE:
  case STATE_PRECHARGE_ERROR:
    break;
  default:
    next_state = NO_CHANGE;
  }

  return next_state;
}


// Function to be executed in state shutdown
// valid return states: NO_CHANGE, STATE_SHUTDOWN
state_t do_shutdown(state_data_t *data) {
  state_t next_state = NO_CHANGE;
  /* Your Code Here */
  
  switch (next_state) {
  case NO_CHANGE:
  case STATE_SHUTDOWN:
    break;
  default:
    next_state = NO_CHANGE;
  }

  return next_state;
}


// Function to be executed in state as_init_error
// valid return states: NO_CHANGE, STATE_AS_INIT_ERROR, STATE_WAIT_DRIVER
state_t do_as_init_error(state_data_t *data) {
  state_t next_state = NO_CHANGE;
  /* Your Code Here */
  
  switch (next_state) {
  case NO_CHANGE:
  case STATE_AS_INIT_ERROR:
  case STATE_WAIT_DRIVER:
    break;
  default:
    next_state = NO_CHANGE;
  }

  return next_state;
}


// Function to be executed in state wait_driver
// valid return states: NO_CHANGE, STATE_WAIT_DRIVER, STATE_ENABLE_AS_DRIVER, STATE_ENABLE_INV_DRIVE, STATE_START_TS_DISCHARGE
state_t do_wait_driver(state_data_t *data) {
  state_t next_state = NO_CHANGE;
  /* Your Code Here */
  
  switch (next_state) {
  case NO_CHANGE:
  case STATE_WAIT_DRIVER:
  case STATE_ENABLE_AS_DRIVER:
  case STATE_ENABLE_INV_DRIVE:
  case STATE_START_TS_DISCHARGE:
    break;
  default:
    next_state = NO_CHANGE;
  }

  return next_state;
}


// Function to be executed in state wait_ts_precharge
// valid return states: NO_CHANGE, STATE_WAIT_TS_PRECHARGE, STATE_PRECHARGE_ERROR, STATE_WAIT_DRIVER
state_t do_wait_ts_precharge(state_data_t *data) {
  state_t next_state = NO_CHANGE;
  /* Your Code Here */
  
  switch (next_state) {
  case NO_CHANGE:
  case STATE_WAIT_TS_PRECHARGE:
  case STATE_PRECHARGE_ERROR:
  case STATE_WAIT_DRIVER:
    break;
  default:
    next_state = NO_CHANGE;
  }

  return next_state;
}


// Function to be executed in state precharge_error
// valid return states: NO_CHANGE, STATE_PRECHARGE_ERROR, STATE_START_TS_DISCHARGE
state_t do_precharge_error(state_data_t *data) {
  state_t next_state = NO_CHANGE;
  /* Your Code Here */
  
  switch (next_state) {
  case NO_CHANGE:
  case STATE_PRECHARGE_ERROR:
  case STATE_START_TS_DISCHARGE:
    break;
  default:
    next_state = NO_CHANGE;
  }

  return next_state;
}


// Function to be executed in state start_ts_discharge
// valid return states: NO_CHANGE, STATE_START_TS_DISCHARGE, STATE_WAIT_TS_DISCHARGE
state_t do_start_ts_discharge(state_data_t *data) {
  state_t next_state = NO_CHANGE;
  /* Your Code Here */
  
  switch (next_state) {
  case NO_CHANGE:
  case STATE_START_TS_DISCHARGE:
  case STATE_WAIT_TS_DISCHARGE:
    break;
  default:
    next_state = NO_CHANGE;
  }

  return next_state;
}


// Function to be executed in state enable_as_driver
// valid return states: NO_CHANGE, STATE_AS_INIT_ERROR, STATE_ENABLE_AS_DRIVER, STATE_CHECK_AS_SETTINGS
state_t do_enable_as_driver(state_data_t *data) {
  state_t next_state = NO_CHANGE;
  /* Your Code Here */
  
  switch (next_state) {
  case NO_CHANGE:
  case STATE_AS_INIT_ERROR:
  case STATE_ENABLE_AS_DRIVER:
  case STATE_CHECK_AS_SETTINGS:
    break;
  default:
    next_state = NO_CHANGE;
  }

  return next_state;
}


// Function to be executed in state enable_inv_drive
// valid return states: NO_CHANGE, STATE_ENABLE_INV_DRIVE, STATE_DRIVE, STATE_DISABLE_INV_DRIVE
state_t do_enable_inv_drive(state_data_t *data) {
  state_t next_state = NO_CHANGE;
  /* Your Code Here */
  
  switch (next_state) {
  case NO_CHANGE:
  case STATE_ENABLE_INV_DRIVE:
  case STATE_DRIVE:
  case STATE_DISABLE_INV_DRIVE:
    break;
  default:
    next_state = NO_CHANGE;
  }

  return next_state;
}


// Function to be executed in state check_as_settings
// valid return states: NO_CHANGE, STATE_AS_INIT_ERROR, STATE_CHECK_AS_SETTINGS, STATE_ENABLE_INV_DRIVE
state_t do_check_as_settings(state_data_t *data) {
  state_t next_state = NO_CHANGE;
  /* Your Code Here */
  
  switch (next_state) {
  case NO_CHANGE:
  case STATE_AS_INIT_ERROR:
  case STATE_CHECK_AS_SETTINGS:
  case STATE_ENABLE_INV_DRIVE:
    break;
  default:
    next_state = NO_CHANGE;
  }

  return next_state;
}


// Function to be executed in state disable_as_driver
// valid return states: STATE_START_TS_DISCHARGE
state_t do_disable_as_driver(state_data_t *data) {
  state_t next_state = STATE_START_TS_DISCHARGE;
  /* Your Code Here */
  
  switch (next_state) {
  case STATE_START_TS_DISCHARGE:
    break;
  default:
    next_state = NO_CHANGE;
  }

  return next_state;
}


// Function to be executed in state drive
// valid return states: NO_CHANGE, STATE_RE_ENABLE_INV_DRIVE, STATE_DRIVE, STATE_DISABLE_INV_DRIVE
state_t do_drive(state_data_t *data) {
  state_t next_state = NO_CHANGE;
  /* Your Code Here */
  
  switch (next_state) {
  case NO_CHANGE:
  case STATE_RE_ENABLE_INV_DRIVE:
  case STATE_DRIVE:
  case STATE_DISABLE_INV_DRIVE:
    break;
  default:
    next_state = NO_CHANGE;
  }

  return next_state;
}


// Function to be executed in state disable_inv_drive
// valid return states: NO_CHANGE, STATE_DISABLE_AS_DRIVER, STATE_DISABLE_INV_DRIVE, STATE_START_TS_DISCHARGE
state_t do_disable_inv_drive(state_data_t *data) {
  state_t next_state = NO_CHANGE;
  /* Your Code Here */
  
  switch (next_state) {
  case NO_CHANGE:
  case STATE_DISABLE_AS_DRIVER:
  case STATE_DISABLE_INV_DRIVE:
  case STATE_START_TS_DISCHARGE:
    break;
  default:
    next_state = NO_CHANGE;
  }

  return next_state;
}


// Function to be executed in state re_enable_inv_drive
// valid return states: STATE_DRIVE
state_t do_re_enable_inv_drive(state_data_t *data) {
  state_t next_state = STATE_DRIVE;
  /* Your Code Here */
  
  switch (next_state) {
  case STATE_DRIVE:
    break;
  default:
    next_state = NO_CHANGE;
  }

  return next_state;
}


// Function to be executed in state wait_ts_discharge
// valid return states: NO_CHANGE, STATE_IDLE, STATE_WAIT_TS_DISCHARGE, STATE_SHUTDOWN
state_t do_wait_ts_discharge(state_data_t *data) {
  state_t next_state = NO_CHANGE;
  /* Your Code Here */
  
  switch (next_state) {
  case NO_CHANGE:
  case STATE_IDLE:
  case STATE_WAIT_TS_DISCHARGE:
  case STATE_SHUTDOWN:
    break;
  default:
    next_state = NO_CHANGE;
  }

  return next_state;
}




/*  ____  _        _        
 * / ___|| |_ __ _| |_ ___  
 * \___ \| __/ _` | __/ _ \
 *  ___) | || (_| | ||  __/ 
 * |____/ \__\__,_|\__\___| 
 *                          
 *                                              
 *  _ __ ___   __ _ _ __   __ _  __ _  ___ _ __ 
 * | '_ ` _ \ / _` | '_ \ / _` |/ _` |/ _ \ '__|
 * | | | | | | (_| | | | | (_| | (_| |  __/ |   
 * |_| |_| |_|\__,_|_| |_|\__,_|\__, |\___|_|   
 *                              |___/           
 */

state_t run_state(state_t cur_state, state_data_t *data) {
  state_t new_state = state_table[cur_state](data);
  if (new_state == NO_CHANGE) new_state = cur_state;

  return new_state;
}



#ifdef TEST_MAIN
#include <unistd.h>
int main() {
  state_t cur_state = STATE_INIT;

  do {
    cur_state = run_state(cur_state, NULL);
    sleep(1);

  } while (1);

  return 0;
}
#endif

