/*!
 * \file pedals-api.h
 * \author Dorijan Di Zepp
 * \date 26-02-2026
 * \brief This file defines the pedals module's API.
 */

#ifndef PEDALS_API_H
#define PEDALS_API_H

#include "pedals.h"

/*!
 * \brief Initializes the pedals internal handler.
 */
enum PedalsReturnCode pedals_api_init();

/*!
 * \brief Allows the setting of the throttle percentage.
 * \note The function checks if the throttle is in a valid range;
 * otherwise, the percentage will be left unchanged.
 * \note If the pedal system is marked as unavailable (is_available == false), 
 * the value will not be updated.
 * \param throttle The throttle position in percentage (0.0f to 1.0f).
 * \return PEDALS_RC_OK on success, PEDALS_RC_ERROR in case of any error.
 */
enum PedalsReturnCode pedals_api_set_throttle(float throttle);

/*!
 * \brief Allows the setting of the brake percentage.
 * \note The function checks if the brake is in a valid range;
 * otherwise, the percentage will be left unchanged.
 * \note If the pedal system is marked as unavailable (is_available == false), 
 * the value will not be updated.
 * \param brake The brake position in percentage (0.0f to 1.0f).
 * \return PEDALS_RC_OK on success, PEDALS_RC_ERROR in case of any error.
 */
enum PedalsReturnCode pedals_api_set_brake(float brake);

/*!
 * \brief Allows the setting of the brake pressure.
 * \note The function checks if the pressure is in a valid range;
 * otherwise, the value will be left unchanged.
 * \note If the pedal system is marked as unavailable (is_available == false), 
 * the value will not be updated.
 * \param brake_pressure The physical brake pressure value.
 * \return PEDALS_RC_OK on success, PEDALS_RC_ERROR in case of any error.
 */
enum PedalsReturnCode pedals_api_set_brake_pressure(float brake_pressure);

/*!
 * \brief Allows to modify the availability state of the pedals.
 * \param is_available Health status of the pedal board connection.
 * \return PEDALS_RC_OK on success, PEDALS_RC_ERROR in case of any error.
 */
enum PedalsReturnCode pedals_api_set_is_available(bool is_available);

/*!
 * \brief Maps current throttle percentage to the driver's requested motor torque.
 * \details This calculates the raw torque request based on the throttle position 
 * and the maximum motor torque (PEDALS_MAX_TORQUE). 
 * \note Safety limits (e.g., 80kW power limit) must be applied by 
 * the inverter control.
 * \return float Desired torque in Nm. Returns 0.0f if the pedals are unavailable.
 */
float pedals_api_get_requested_throttle_torque();

/*!
 * \brief Checks if the brake pedal is sufficiently pressed.
 * \details Uses a predefined threshold to determine if the 
 * driver is holding the car stationary.
 * \return true if the brake is pressed and the module is available.
 * \note Returns false if the system is unavailable to prevent accidental 
 * R2D activation in the event of a communication loss.
 */
bool pedals_api_is_brake_pressed();

/*!
 * \brief Return the latest throttle percentage received.
 * \return float value indicating the position of the throttle pedal in percentage
 */
float pedals_api_get_throttle();

/*!
 * \brief Return the latest brake percentage received.
 * \return float value indicating the position of the brake pedal in percentage
 */
float pedals_api_get_brake();

/*!
 * \brief Return the latest brake pressure received.
 * \return float value indicating the pressure generated by the brake pedal in bars.
 */
float pedals_api_get_brake_pressure();

/*!
 * \brief Function to determine the availability of the pedals
 * \return true if the pedals are availabele, false otherwise
 */
bool pedals_api_get_is_available();

#endif