/******************************************************************************
Finite State Machine
Project: fsm.dot
Description: ecu_fsm

Generated by gv_fsm ruby gem, see https://rubygems.org/gems/gv_fsm
gv_fsm version 0.5.2
Generation date: 2026-05-07 20:58:07 +0200
Generated from: fsm.dot
The finite state machine has:
  13 states
  2 transition functions

******************************************************************************/

#ifndef ECU_FSM_H
#define ECU_FSM_H
#ifdef __cplusplus
extern "C" {
#endif
#include <stdlib.h>

// State data object
// By default set to void; override this typedef or load the proper
// header if you need
typedef void state_data_t;

// NOTHING SHALL BE CHANGED AFTER THIS LINE!

// List of states
typedef enum {
    STATE_INIT = 0,
    STATE_FATAL,
    STATE_IDLE,
    STATE_FLASH,
    STATE_PAUSE,
    STATE_WAIT_TS_PRECHARGE,
    STATE_WAIT_DRIVER,
    STATE_WAIT_TS_DISCHARGE,
    STATE_ENABLE_AS_DRIVER,
    STATE_ENABLE_INV_DRIVE,
    STATE_DISABLE_AS_DRIVER,
    STATE_DISABLE_INV_DRIVE,
    STATE_R2D,
    NUM_STATES,
    NO_CHANGE
} state_t;

// State human-readable names
extern const char *state_names[];

// State function and state transition prototypes
typedef state_t state_func_t(state_data_t *data);
typedef void transition_func_t(state_data_t *data);

// State functions
// Function to be executed in state init
// valid return states: STATE_FATAL, STATE_IDLE
state_t do_init(state_data_t *data);
// Function to be executed in state fatal
// valid return states: NO_CHANGE, STATE_FATAL
state_t do_fatal(state_data_t *data);
// Function to be executed in state idle
// valid return states: NO_CHANGE, STATE_FLASH, STATE_PAUSE, STATE_FATAL, STATE_IDLE, STATE_WAIT_TS_PRECHARGE
state_t do_idle(state_data_t *data);
// Function to be executed in state flash
// valid return states: NO_CHANGE, STATE_FLASH, STATE_IDLE
state_t do_flash(state_data_t *data);
// Function to be executed in state pause
// valid return states: NO_CHANGE, STATE_PAUSE, STATE_IDLE
state_t do_pause(state_data_t *data);
// Function to be executed in state wait_ts_precharge
// valid return states: NO_CHANGE, STATE_WAIT_TS_PRECHARGE, STATE_WAIT_DRIVER, STATE_WAIT_TS_DISCHARGE
state_t do_wait_ts_precharge(state_data_t *data);
// Function to be executed in state wait_driver
// valid return states: NO_CHANGE, STATE_WAIT_DRIVER, STATE_ENABLE_AS_DRIVER, STATE_ENABLE_INV_DRIVE, STATE_WAIT_TS_DISCHARGE
state_t do_wait_driver(state_data_t *data);
// Function to be executed in state wait_ts_discharge
// valid return states: NO_CHANGE, STATE_IDLE, STATE_WAIT_TS_DISCHARGE
state_t do_wait_ts_discharge(state_data_t *data);
// Function to be executed in state enable_as_driver
// valid return states: NO_CHANGE, STATE_ENABLE_AS_DRIVER, STATE_ENABLE_INV_DRIVE, STATE_WAIT_TS_DISCHARGE
state_t do_enable_as_driver(state_data_t *data);
// Function to be executed in state enable_inv_drive
// valid return states: NO_CHANGE, STATE_ENABLE_INV_DRIVE, STATE_DISABLE_INV_DRIVE, STATE_R2D
state_t do_enable_inv_drive(state_data_t *data);
// Function to be executed in state disable_as_driver
// valid return states: NO_CHANGE, STATE_DISABLE_AS_DRIVER, STATE_DISABLE_INV_DRIVE
state_t do_disable_as_driver(state_data_t *data);
// Function to be executed in state disable_inv_drive
// valid return states: NO_CHANGE, STATE_DISABLE_INV_DRIVE, STATE_WAIT_TS_DISCHARGE
state_t do_disable_inv_drive(state_data_t *data);
// Function to be executed in state r2d
// valid return states: NO_CHANGE, STATE_DISABLE_AS_DRIVER, STATE_DISABLE_INV_DRIVE, STATE_R2D
state_t do_r2d(state_data_t *data);

// List of state functions
extern state_func_t *const state_table[NUM_STATES];

// Transition functions
void start_ts_precharge(state_data_t *data);
void start_ts_discharge(state_data_t *data);

// Table of transition functions
extern transition_func_t *const transition_table[NUM_STATES][NUM_STATES];

// state manager
state_t run_state(state_t cur_state, state_data_t *data);

#ifdef __cplusplus
}
#endif
#endif // ECU_FSM_H