/******************************************************************************
Finite State Machine
Project: ecu-fsm.dot
Description: ecu_fsm

Generated by gv_fsm ruby gem, see https://rubygems.org/gems/gv_fsm
gv_fsm version 0.5.2
Generation date: 2026-05-28 16:02:52 +0200
Generated from: ecu-fsm.dot
The finite state machine has:
  25 states
  4 transition functions

******************************************************************************/

#ifndef ECU_FSM_H
#define ECU_FSM_H
#ifdef __cplusplus
extern "C" {
#endif
#include <stdlib.h>

// USER includes ------------------
#include "as-driver-api.h"
#include "buzzer-api.h"
#include "can-communication-api.h"
#include "can-communication-router-api.h"
#include "inverters-api.h"
#include "logger-api.h"
#include "pedals-api.h"
#include "post-api.h"
#include "raspberry-api.h"
#include "tractive-system-api.h"
#include "vehicle-api.h"
#include "eagletrt-api.h"
// END USER includes --------------

// State data object
// By default set to void; override this typedef or load the proper
// header if you need
typedef void state_data_t;

// NOTHING SHALL BE CHANGED AFTER THIS LINE!

// List of states
typedef enum {
    STATE_INIT = 0,
    STATE_FATAL,
    STATE_IDLE,
    STATE_FLASH,
    STATE_PAUSE,
    STATE_MANUAL_WAIT_TS_PRECHARGE,
    STATE_AS_OFF,
    STATE_WAIT_DRIVER,
    STATE_MANUAL_WAIT_TS_DISCHARGE,
    STATE_MANUAL_WAIT_INV_ENABLE,
    STATE_DRIVING,
    STATE_MANUAL_WAIT_INV_DISABLE,
    STATE_AS_OFF_WAIT_TS_PRECHARGE,
    STATE_AS_READY,
    STATE_AS_READY_WAIT_INV_ENABLE,
    STATE_AS_EMERGENCY,
    STATE_AS_R2D,
    STATE_AS_DRIVING,
    STATE_AS_FINISHED,
    STATE_AS_OFF_WAIT_TS_DISCHARGE,
    STATE_AS_READY_WAIT_INV_DISABLE,
    STATE_AS_FINISHED_WAIT_INV_DISABLE,
    STATE_AS_FINISHED_WAIT_TS_DISCHARGE,
    STATE_AS_EMERGENCY_WAIT_INV_DISABLE,
    STATE_AS_EMERGENCY_WAIT_TS_DISCHARGE,
    NUM_STATES,
    NO_CHANGE
} state_t;

// State human-readable names
extern const char *state_names[];

// State function and state transition prototypes
typedef state_t state_func_t(state_data_t *data);
typedef void transition_func_t(state_data_t *data);

// State functions
// Function to be executed in state init
// valid return states: STATE_FATAL, STATE_IDLE
state_t do_init(state_data_t *data);
// Function to be executed in state fatal
// valid return states: NO_CHANGE, STATE_FATAL
state_t do_fatal(state_data_t *data);
// Function to be executed in state idle
// valid return states: NO_CHANGE, STATE_FLASH, STATE_PAUSE, STATE_FATAL, STATE_IDLE, STATE_MANUAL_WAIT_TS_PRECHARGE, STATE_AS_OFF
state_t do_idle(state_data_t *data);
// Function to be executed in state flash
// valid return states: NO_CHANGE, STATE_FLASH, STATE_IDLE
state_t do_flash(state_data_t *data);
// Function to be executed in state pause
// valid return states: NO_CHANGE, STATE_PAUSE, STATE_IDLE
state_t do_pause(state_data_t *data);
// Function to be executed in state manual_wait_ts_precharge
// valid return states: NO_CHANGE, STATE_MANUAL_WAIT_TS_PRECHARGE, STATE_WAIT_DRIVER, STATE_MANUAL_WAIT_TS_DISCHARGE
state_t do_manual_wait_ts_precharge(state_data_t *data);
// Function to be executed in state as_off
// valid return states: NO_CHANGE, STATE_FATAL, STATE_IDLE, STATE_AS_OFF, STATE_AS_OFF_WAIT_TS_PRECHARGE
state_t do_as_off(state_data_t *data);
// Function to be executed in state wait_driver
// valid return states: NO_CHANGE, STATE_WAIT_DRIVER, STATE_MANUAL_WAIT_INV_ENABLE, STATE_MANUAL_WAIT_TS_DISCHARGE
state_t do_wait_driver(state_data_t *data);
// Function to be executed in state manual_wait_ts_discharge
// valid return states: NO_CHANGE, STATE_IDLE, STATE_MANUAL_WAIT_TS_DISCHARGE
state_t do_manual_wait_ts_discharge(state_data_t *data);
// Function to be executed in state manual_wait_inv_enable
// valid return states: NO_CHANGE, STATE_MANUAL_WAIT_INV_ENABLE, STATE_DRIVING, STATE_MANUAL_WAIT_INV_DISABLE
state_t do_manual_wait_inv_enable(state_data_t *data);
// Function to be executed in state driving
// valid return states: NO_CHANGE, STATE_DRIVING, STATE_MANUAL_WAIT_INV_DISABLE
state_t do_driving(state_data_t *data);
// Function to be executed in state manual_wait_inv_disable
// valid return states: NO_CHANGE, STATE_MANUAL_WAIT_INV_DISABLE, STATE_MANUAL_WAIT_TS_DISCHARGE
state_t do_manual_wait_inv_disable(state_data_t *data);
// Function to be executed in state as_off_wait_ts_precharge
// valid return states: NO_CHANGE, STATE_AS_READY, STATE_AS_OFF_WAIT_TS_PRECHARGE, STATE_AS_OFF_WAIT_TS_DISCHARGE
state_t do_as_off_wait_ts_precharge(state_data_t *data);
// Function to be executed in state as_ready
// valid return states: NO_CHANGE, STATE_AS_READY, STATE_AS_READY_WAIT_INV_ENABLE, STATE_AS_EMERGENCY
state_t do_as_ready(state_data_t *data);
// Function to be executed in state as_ready_wait_inv_enable
// valid return states: NO_CHANGE, STATE_AS_R2D, STATE_AS_READY_WAIT_INV_ENABLE, STATE_AS_READY_WAIT_INV_DISABLE
state_t do_as_ready_wait_inv_enable(state_data_t *data);
// Function to be executed in state as_emergency
// valid return states: NO_CHANGE, STATE_AS_EMERGENCY, STATE_AS_EMERGENCY_WAIT_INV_DISABLE
state_t do_as_emergency(state_data_t *data);
// Function to be executed in state as_r2d
// valid return states: STATE_AS_DRIVING, STATE_AS_EMERGENCY
state_t do_as_r2d(state_data_t *data);
// Function to be executed in state as_driving
// valid return states: NO_CHANGE, STATE_AS_DRIVING, STATE_AS_FINISHED, STATE_AS_EMERGENCY
state_t do_as_driving(state_data_t *data);
// Function to be executed in state as_finished
// valid return states: NO_CHANGE, STATE_AS_FINISHED, STATE_AS_FINISHED_WAIT_INV_DISABLE
state_t do_as_finished(state_data_t *data);
// Function to be executed in state as_off_wait_ts_discharge
// valid return states: NO_CHANGE, STATE_AS_OFF, STATE_AS_OFF_WAIT_TS_DISCHARGE
state_t do_as_off_wait_ts_discharge(state_data_t *data);
// Function to be executed in state as_ready_wait_inv_disable
// valid return states: NO_CHANGE, STATE_AS_READY_WAIT_INV_DISABLE, STATE_AS_EMERGENCY
state_t do_as_ready_wait_inv_disable(state_data_t *data);
// Function to be executed in state as_finished_wait_inv_disable
// valid return states: NO_CHANGE, STATE_AS_FINISHED_WAIT_INV_DISABLE, STATE_AS_FINISHED_WAIT_TS_DISCHARGE
state_t do_as_finished_wait_inv_disable(state_data_t *data);
// Function to be executed in state as_finished_wait_ts_discharge
// valid return states: NO_CHANGE, STATE_AS_FINISHED, STATE_AS_FINISHED_WAIT_TS_DISCHARGE
state_t do_as_finished_wait_ts_discharge(state_data_t *data);
// Function to be executed in state as_emergency_wait_inv_disable
// valid return states: NO_CHANGE, STATE_AS_EMERGENCY_WAIT_INV_DISABLE, STATE_AS_EMERGENCY_WAIT_TS_DISCHARGE
state_t do_as_emergency_wait_inv_disable(state_data_t *data);
// Function to be executed in state as_emergency_wait_ts_discharge
// valid return states: NO_CHANGE, STATE_AS_EMERGENCY, STATE_AS_EMERGENCY_WAIT_TS_DISCHARGE
state_t do_as_emergency_wait_ts_discharge(state_data_t *data);

// List of state functions
extern state_func_t *const state_table[NUM_STATES];

// Transition functions
void start_ts_precharge(state_data_t *data);
void start_ts_discharge(state_data_t *data);
void start_inv_enable(state_data_t *data);
void start_inv_disable(state_data_t *data);

// Table of transition functions
extern transition_func_t *const transition_table[NUM_STATES][NUM_STATES];

// state manager
state_t run_state(state_t cur_state, state_data_t *data);

#ifdef __cplusplus
}
#endif
#endif // ECU_FSM_H