/******************************************************************************
Finite State Machine
Project: ecu-fsm.dot
Description: ecu_fsm

Generated by gv_fsm ruby gem, see https://rubygems.org/gems/gv_fsm
gv_fsm version 0.5.2
Generation date: 2026-05-28 16:02:52 +0200
Generated from: ecu-fsm.dot
The finite state machine has:
  25 states
  4 transition functions

******************************************************************************/

#include "ecu_fsm.h"

// SEARCH FOR Your Code Here FOR CODE INSERTION POINTS!

// GLOBALS
// State human-readable names
const char *state_names[] = { "init", "fatal", "idle", "flash", "pause", "manual_wait_ts_precharge", "as_off", "wait_driver", "manual_wait_ts_discharge", "manual_wait_inv_enable", "driving", "manual_wait_inv_disable", "as_off_wait_ts_precharge", "as_ready", "as_ready_wait_inv_enable", "as_emergency", "as_r2d", "as_driving", "as_finished", "as_off_wait_ts_discharge", "as_ready_wait_inv_disable", "as_finished_wait_inv_disable", "as_finished_wait_ts_discharge", "as_emergency_wait_inv_disable", "as_emergency_wait_ts_discharge" };

// List of state functions
state_func_t *const state_table[NUM_STATES] = {
    do_init,                           // in state init
    do_fatal,                          // in state fatal
    do_idle,                           // in state idle
    do_flash,                          // in state flash
    do_pause,                          // in state pause
    do_manual_wait_ts_precharge,       // in state manual_wait_ts_precharge
    do_as_off,                         // in state as_off
    do_wait_driver,                    // in state wait_driver
    do_manual_wait_ts_discharge,       // in state manual_wait_ts_discharge
    do_manual_wait_inv_enable,         // in state manual_wait_inv_enable
    do_driving,                        // in state driving
    do_manual_wait_inv_disable,        // in state manual_wait_inv_disable
    do_as_off_wait_ts_precharge,       // in state as_off_wait_ts_precharge
    do_as_ready,                       // in state as_ready
    do_as_ready_wait_inv_enable,       // in state as_ready_wait_inv_enable
    do_as_emergency,                   // in state as_emergency
    do_as_r2d,                         // in state as_r2d
    do_as_driving,                     // in state as_driving
    do_as_finished,                    // in state as_finished
    do_as_off_wait_ts_discharge,       // in state as_off_wait_ts_discharge
    do_as_ready_wait_inv_disable,      // in state as_ready_wait_inv_disable
    do_as_finished_wait_inv_disable,   // in state as_finished_wait_inv_disable
    do_as_finished_wait_ts_discharge,  // in state as_finished_wait_ts_discharge
    do_as_emergency_wait_inv_disable,  // in state as_emergency_wait_inv_disable
    do_as_emergency_wait_ts_discharge, // in state as_emergency_wait_ts_discharge
};

// Table of transition functions
transition_func_t *const transition_table[NUM_STATES][NUM_STATES] = {
    /* states:                            init              , fatal             , idle              , flash             , pause             , manual_wait_ts_precharge, as_off            , wait_driver       , manual_wait_ts_discharge, manual_wait_inv_enable, driving           , manual_wait_inv_disable, as_off_wait_ts_precharge, as_ready          , as_ready_wait_inv_enable, as_emergency      , as_r2d            , as_driving        , as_finished       , as_off_wait_ts_discharge, as_ready_wait_inv_disable, as_finished_wait_inv_disable, as_finished_wait_ts_discharge, as_emergency_wait_inv_disable, as_emergency_wait_ts_discharge */
    /* init                           */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* fatal                          */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* idle                           */ { NULL, NULL, NULL, NULL, NULL, start_ts_precharge, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* flash                          */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* pause                          */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* manual_wait_ts_precharge       */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, start_ts_discharge, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* as_off                         */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, start_ts_precharge, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* wait_driver                    */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, start_ts_discharge, start_inv_enable, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* manual_wait_ts_discharge       */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* manual_wait_inv_enable         */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, start_inv_disable, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* driving                        */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, start_inv_disable, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* manual_wait_inv_disable        */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, start_ts_discharge, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* as_off_wait_ts_precharge       */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, start_ts_discharge, NULL, NULL, NULL, NULL, NULL },
    /* as_ready                       */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, start_inv_enable, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* as_ready_wait_inv_enable       */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, start_inv_disable, NULL, NULL, NULL, NULL },
    /* as_emergency                   */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, start_inv_disable, NULL },
    /* as_r2d                         */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* as_driving                     */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* as_finished                    */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, start_inv_disable, NULL, NULL, NULL },
    /* as_off_wait_ts_discharge       */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* as_ready_wait_inv_disable      */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* as_finished_wait_inv_disable   */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, start_ts_discharge, NULL, NULL },
    /* as_finished_wait_ts_discharge  */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* as_emergency_wait_inv_disable  */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, start_ts_discharge },
    /* as_emergency_wait_ts_discharge */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
};

/*  ____  _        _       
 * / ___|| |_ __ _| |_ ___ 
 * \___ \| __/ _` | __/ _ \
 *  ___) | || (_| | ||  __/
 * |____/ \__\__,_|\__\___|
 *                         
 *   __                  _   _                 
 *  / _|_   _ _ __   ___| |_(_) ___  _ __  ___ 
 * | |_| | | | '_ \ / __| __| |/ _ \| '_ \/ __|
 * |  _| |_| | | | | (__| |_| | (_) | | | \__ \
 * |_|  \__,_|_| |_|\___|\__|_|\___/|_| |_|___/
 */

// Function to be executed in state init
// valid return states: STATE_FATAL, STATE_IDLE
state_t do_init(state_data_t *data) {
    state_t next_state = STATE_FATAL;
    /* Your Code Here */

    switch (next_state) {
        case STATE_FATAL:
        case STATE_IDLE:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state fatal
// valid return states: NO_CHANGE, STATE_FATAL
state_t do_fatal(state_data_t *data) {
    state_t next_state = NO_CHANGE;
    /* Your Code Here */

    switch (next_state) {
        case NO_CHANGE:
        case STATE_FATAL:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state idle
// valid return states: NO_CHANGE, STATE_FLASH, STATE_PAUSE, STATE_FATAL, STATE_IDLE, STATE_MANUAL_WAIT_TS_PRECHARGE, STATE_AS_OFF
state_t do_idle(state_data_t *data) {
    state_t next_state = NO_CHANGE;
    /* Your Code Here */

    switch (next_state) {
        case NO_CHANGE:
        case STATE_FLASH:
        case STATE_PAUSE:
        case STATE_FATAL:
        case STATE_IDLE:
        case STATE_MANUAL_WAIT_TS_PRECHARGE:
        case STATE_AS_OFF:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state flash
// valid return states: NO_CHANGE, STATE_FLASH, STATE_IDLE
state_t do_flash(state_data_t *data) {
    state_t next_state = NO_CHANGE;
    /* Your Code Here */

    switch (next_state) {
        case NO_CHANGE:
        case STATE_FLASH:
        case STATE_IDLE:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state pause
// valid return states: NO_CHANGE, STATE_PAUSE, STATE_IDLE
state_t do_pause(state_data_t *data) {
    state_t next_state = NO_CHANGE;
    /* Your Code Here */

    switch (next_state) {
        case NO_CHANGE:
        case STATE_PAUSE:
        case STATE_IDLE:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state manual_wait_ts_precharge
// valid return states: NO_CHANGE, STATE_MANUAL_WAIT_TS_PRECHARGE, STATE_WAIT_DRIVER, STATE_MANUAL_WAIT_TS_DISCHARGE
state_t do_manual_wait_ts_precharge(state_data_t *data) {
    state_t next_state = NO_CHANGE;
    /* Your Code Here */

    switch (next_state) {
        case NO_CHANGE:
        case STATE_MANUAL_WAIT_TS_PRECHARGE:
        case STATE_WAIT_DRIVER:
        case STATE_MANUAL_WAIT_TS_DISCHARGE:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state as_off
// valid return states: NO_CHANGE, STATE_FATAL, STATE_IDLE, STATE_AS_OFF, STATE_AS_OFF_WAIT_TS_PRECHARGE
state_t do_as_off(state_data_t *data) {
    state_t next_state = NO_CHANGE;
    /* Your Code Here */

    switch (next_state) {
        case NO_CHANGE:
        case STATE_FATAL:
        case STATE_IDLE:
        case STATE_AS_OFF:
        case STATE_AS_OFF_WAIT_TS_PRECHARGE:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state wait_driver
// valid return states: NO_CHANGE, STATE_WAIT_DRIVER, STATE_MANUAL_WAIT_INV_ENABLE, STATE_MANUAL_WAIT_TS_DISCHARGE
state_t do_wait_driver(state_data_t *data) {
    state_t next_state = NO_CHANGE;
    /* Your Code Here */

    switch (next_state) {
        case NO_CHANGE:
        case STATE_WAIT_DRIVER:
        case STATE_MANUAL_WAIT_INV_ENABLE:
        case STATE_MANUAL_WAIT_TS_DISCHARGE:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state manual_wait_ts_discharge
// valid return states: NO_CHANGE, STATE_IDLE, STATE_MANUAL_WAIT_TS_DISCHARGE
state_t do_manual_wait_ts_discharge(state_data_t *data) {
    state_t next_state = NO_CHANGE;
    /* Your Code Here */

    switch (next_state) {
        case NO_CHANGE:
        case STATE_IDLE:
        case STATE_MANUAL_WAIT_TS_DISCHARGE:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state manual_wait_inv_enable
// valid return states: NO_CHANGE, STATE_MANUAL_WAIT_INV_ENABLE, STATE_DRIVING, STATE_MANUAL_WAIT_INV_DISABLE
state_t do_manual_wait_inv_enable(state_data_t *data) {
    state_t next_state = NO_CHANGE;
    /* Your Code Here */

    switch (next_state) {
        case NO_CHANGE:
        case STATE_MANUAL_WAIT_INV_ENABLE:
        case STATE_DRIVING:
        case STATE_MANUAL_WAIT_INV_DISABLE:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state driving
// valid return states: NO_CHANGE, STATE_DRIVING, STATE_MANUAL_WAIT_INV_DISABLE
state_t do_driving(state_data_t *data) {
    state_t next_state = NO_CHANGE;
    /* Your Code Here */

    switch (next_state) {
        case NO_CHANGE:
        case STATE_DRIVING:
        case STATE_MANUAL_WAIT_INV_DISABLE:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state manual_wait_inv_disable
// valid return states: NO_CHANGE, STATE_MANUAL_WAIT_INV_DISABLE, STATE_MANUAL_WAIT_TS_DISCHARGE
state_t do_manual_wait_inv_disable(state_data_t *data) {
    state_t next_state = NO_CHANGE;
    /* Your Code Here */

    switch (next_state) {
        case NO_CHANGE:
        case STATE_MANUAL_WAIT_INV_DISABLE:
        case STATE_MANUAL_WAIT_TS_DISCHARGE:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state as_off_wait_ts_precharge
// valid return states: NO_CHANGE, STATE_AS_READY, STATE_AS_OFF_WAIT_TS_PRECHARGE, STATE_AS_OFF_WAIT_TS_DISCHARGE
state_t do_as_off_wait_ts_precharge(state_data_t *data) {
    state_t next_state = NO_CHANGE;
    /* Your Code Here */

    switch (next_state) {
        case NO_CHANGE:
        case STATE_AS_READY:
        case STATE_AS_OFF_WAIT_TS_PRECHARGE:
        case STATE_AS_OFF_WAIT_TS_DISCHARGE:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state as_ready
// valid return states: NO_CHANGE, STATE_AS_READY, STATE_AS_READY_WAIT_INV_ENABLE, STATE_AS_EMERGENCY
state_t do_as_ready(state_data_t *data) {
    state_t next_state = NO_CHANGE;
    /* Your Code Here */

    switch (next_state) {
        case NO_CHANGE:
        case STATE_AS_READY:
        case STATE_AS_READY_WAIT_INV_ENABLE:
        case STATE_AS_EMERGENCY:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state as_ready_wait_inv_enable
// valid return states: NO_CHANGE, STATE_AS_R2D, STATE_AS_READY_WAIT_INV_ENABLE, STATE_AS_READY_WAIT_INV_DISABLE
state_t do_as_ready_wait_inv_enable(state_data_t *data) {
    state_t next_state = NO_CHANGE;
    /* Your Code Here */

    switch (next_state) {
        case NO_CHANGE:
        case STATE_AS_R2D:
        case STATE_AS_READY_WAIT_INV_ENABLE:
        case STATE_AS_READY_WAIT_INV_DISABLE:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state as_emergency
// valid return states: NO_CHANGE, STATE_AS_EMERGENCY, STATE_AS_EMERGENCY_WAIT_INV_DISABLE
state_t do_as_emergency(state_data_t *data) {
    state_t next_state = NO_CHANGE;
    /* Your Code Here */

    switch (next_state) {
        case NO_CHANGE:
        case STATE_AS_EMERGENCY:
        case STATE_AS_EMERGENCY_WAIT_INV_DISABLE:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state as_r2d
// valid return states: STATE_AS_DRIVING, STATE_AS_EMERGENCY
state_t do_as_r2d(state_data_t *data) {
    state_t next_state = STATE_AS_DRIVING;
    /* Your Code Here */

    switch (next_state) {
        case STATE_AS_DRIVING:
        case STATE_AS_EMERGENCY:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state as_driving
// valid return states: NO_CHANGE, STATE_AS_DRIVING, STATE_AS_FINISHED, STATE_AS_EMERGENCY
state_t do_as_driving(state_data_t *data) {
    state_t next_state = NO_CHANGE;
    /* Your Code Here */

    switch (next_state) {
        case NO_CHANGE:
        case STATE_AS_DRIVING:
        case STATE_AS_FINISHED:
        case STATE_AS_EMERGENCY:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state as_finished
// valid return states: NO_CHANGE, STATE_AS_FINISHED, STATE_AS_FINISHED_WAIT_INV_DISABLE
state_t do_as_finished(state_data_t *data) {
    state_t next_state = NO_CHANGE;
    /* Your Code Here */

    switch (next_state) {
        case NO_CHANGE:
        case STATE_AS_FINISHED:
        case STATE_AS_FINISHED_WAIT_INV_DISABLE:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state as_off_wait_ts_discharge
// valid return states: NO_CHANGE, STATE_AS_OFF, STATE_AS_OFF_WAIT_TS_DISCHARGE
state_t do_as_off_wait_ts_discharge(state_data_t *data) {
    state_t next_state = NO_CHANGE;
    /* Your Code Here */

    switch (next_state) {
        case NO_CHANGE:
        case STATE_AS_OFF:
        case STATE_AS_OFF_WAIT_TS_DISCHARGE:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state as_ready_wait_inv_disable
// valid return states: NO_CHANGE, STATE_AS_READY_WAIT_INV_DISABLE, STATE_AS_EMERGENCY
state_t do_as_ready_wait_inv_disable(state_data_t *data) {
    state_t next_state = NO_CHANGE;
    /* Your Code Here */

    switch (next_state) {
        case NO_CHANGE:
        case STATE_AS_READY_WAIT_INV_DISABLE:
        case STATE_AS_EMERGENCY:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state as_finished_wait_inv_disable
// valid return states: NO_CHANGE, STATE_AS_FINISHED_WAIT_INV_DISABLE, STATE_AS_FINISHED_WAIT_TS_DISCHARGE
state_t do_as_finished_wait_inv_disable(state_data_t *data) {
    state_t next_state = NO_CHANGE;
    /* Your Code Here */

    switch (next_state) {
        case NO_CHANGE:
        case STATE_AS_FINISHED_WAIT_INV_DISABLE:
        case STATE_AS_FINISHED_WAIT_TS_DISCHARGE:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state as_finished_wait_ts_discharge
// valid return states: NO_CHANGE, STATE_AS_FINISHED, STATE_AS_FINISHED_WAIT_TS_DISCHARGE
state_t do_as_finished_wait_ts_discharge(state_data_t *data) {
    state_t next_state = NO_CHANGE;
    /* Your Code Here */

    switch (next_state) {
        case NO_CHANGE:
        case STATE_AS_FINISHED:
        case STATE_AS_FINISHED_WAIT_TS_DISCHARGE:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state as_emergency_wait_inv_disable
// valid return states: NO_CHANGE, STATE_AS_EMERGENCY_WAIT_INV_DISABLE, STATE_AS_EMERGENCY_WAIT_TS_DISCHARGE
state_t do_as_emergency_wait_inv_disable(state_data_t *data) {
    state_t next_state = NO_CHANGE;
    /* Your Code Here */

    switch (next_state) {
        case NO_CHANGE:
        case STATE_AS_EMERGENCY_WAIT_INV_DISABLE:
        case STATE_AS_EMERGENCY_WAIT_TS_DISCHARGE:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state as_emergency_wait_ts_discharge
// valid return states: NO_CHANGE, STATE_AS_EMERGENCY, STATE_AS_EMERGENCY_WAIT_TS_DISCHARGE
state_t do_as_emergency_wait_ts_discharge(state_data_t *data) {
    state_t next_state = NO_CHANGE;
    /* Your Code Here */

    switch (next_state) {
        case NO_CHANGE:
        case STATE_AS_EMERGENCY:
        case STATE_AS_EMERGENCY_WAIT_TS_DISCHARGE:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

/*  _____                    _ _   _              
 * |_   _| __ __ _ _ __  ___(_) |_(_) ___  _ __   
 *   | || '__/ _` | '_ \/ __| | __| |/ _ \| '_ \
 *   | || | | (_| | | | \__ \ | |_| | (_) | | | | 
 *   |_||_|  \__,_|_| |_|___/_|\__|_|\___/|_| |_| 
 *                                                
 *   __                  _   _                 
 *  / _|_   _ _ __   ___| |_(_) ___  _ __  ___ 
 * | |_| | | | '_ \ / __| __| |/ _ \| '_ \/ __|
 * |  _| |_| | | | | (__| |_| | (_) | | | \__ \
 * |_|  \__,_|_| |_|\___|\__|_|\___/|_| |_|___/
 */

// This function is called in 2 transitions:
// 1. from idle to manual_wait_ts_precharge
// 2. from as_off to as_off_wait_ts_precharge
void start_ts_precharge(state_data_t *data) {
    /* Your Code Here */
}

// This function is called in 6 transitions:
// 1. from manual_wait_ts_precharge to manual_wait_ts_discharge
// 2. from wait_driver to manual_wait_ts_discharge
// 3. from manual_wait_inv_disable to manual_wait_ts_discharge
// 4. from as_off_wait_ts_precharge to as_off_wait_ts_discharge
// 5. from as_finished_wait_inv_disable to as_finished_wait_ts_discharge
// 6. from as_emergency_wait_inv_disable to as_emergency_wait_ts_discharge
void start_ts_discharge(state_data_t *data) {
    /* Your Code Here */
}

// This function is called in 2 transitions:
// 1. from wait_driver to manual_wait_inv_enable
// 2. from as_ready to as_ready_wait_inv_enable
void start_inv_enable(state_data_t *data) {
    /* Your Code Here */
}

// This function is called in 5 transitions:
// 1. from manual_wait_inv_enable to manual_wait_inv_disable
// 2. from driving to manual_wait_inv_disable
// 3. from as_ready_wait_inv_enable to as_ready_wait_inv_disable
// 4. from as_finished to as_finished_wait_inv_disable
// 5. from as_emergency to as_emergency_wait_inv_disable
void start_inv_disable(state_data_t *data) {
    /* Your Code Here */
}

/*  ____  _        _        
 * / ___|| |_ __ _| |_ ___  
 * \___ \| __/ _` | __/ _ \
 *  ___) | || (_| | ||  __/ 
 * |____/ \__\__,_|\__\___| 
 *                          
 *                                              
 *  _ __ ___   __ _ _ __   __ _  __ _  ___ _ __ 
 * | '_ ` _ \ / _` | '_ \ / _` |/ _` |/ _ \ '__|
 * | | | | | | (_| | | | | (_| | (_| |  __/ |   
 * |_| |_| |_|\__,_|_| |_|\__,_|\__, |\___|_|   
 *                              |___/           
 */

state_t run_state(state_t cur_state, state_data_t *data) {
    state_t new_state = state_table[cur_state](data);
    if (new_state == NO_CHANGE)
        new_state = cur_state;

    transition_func_t *transition = transition_table[cur_state][new_state];
    if (transition) {
        transition(data);
    }

    return new_state;
}

#ifdef TEST_MAIN
#include <unistd.h>
int main() {
    state_t cur_state = STATE_INIT;

    do {
        cur_state = run_state(cur_state, NULL);
        sleep(1);

    } while (1);

    return 0;
}
#endif
