/******************************************************************************
Finite State Machine
Project: fsm.dot
Description: ecu_fsm

Generated by gv_fsm ruby gem, see https://rubygems.org/gems/gv_fsm
gv_fsm version 0.5.2
Generation date: 2026-05-07 20:58:07 +0200
Generated from: fsm.dot
The finite state machine has:
  13 states
  2 transition functions

******************************************************************************/

#include "ecu_fsm.h"

// SEARCH FOR Your Code Here FOR CODE INSERTION POINTS!

// GLOBALS
// State human-readable names
const char *state_names[] = { "init", "fatal", "idle", "flash", "pause", "wait_ts_precharge", "wait_driver", "wait_ts_discharge", "enable_as_driver", "enable_inv_drive", "disable_as_driver", "disable_inv_drive", "r2d" };

// List of state functions
state_func_t *const state_table[NUM_STATES] = {
    do_init,              // in state init
    do_fatal,             // in state fatal
    do_idle,              // in state idle
    do_flash,             // in state flash
    do_pause,             // in state pause
    do_wait_ts_precharge, // in state wait_ts_precharge
    do_wait_driver,       // in state wait_driver
    do_wait_ts_discharge, // in state wait_ts_discharge
    do_enable_as_driver,  // in state enable_as_driver
    do_enable_inv_drive,  // in state enable_inv_drive
    do_disable_as_driver, // in state disable_as_driver
    do_disable_inv_drive, // in state disable_inv_drive
    do_r2d,               // in state r2d
};

// Table of transition functions
transition_func_t *const transition_table[NUM_STATES][NUM_STATES] = {
    /* states:               init              , fatal             , idle              , flash             , pause             , wait_ts_precharge , wait_driver       , wait_ts_discharge , enable_as_driver  , enable_inv_drive  , disable_as_driver , disable_inv_drive , r2d                */
    /* init              */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* fatal             */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* idle              */ { NULL, NULL, NULL, NULL, NULL, start_ts_precharge, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* flash             */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* pause             */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* wait_ts_precharge */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, start_ts_discharge, NULL, NULL, NULL, NULL, NULL },
    /* wait_driver       */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, start_ts_discharge, NULL, NULL, NULL, NULL, NULL },
    /* wait_ts_discharge */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* enable_as_driver  */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, start_ts_discharge, NULL, NULL, NULL, NULL, NULL },
    /* enable_inv_drive  */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* disable_as_driver */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* disable_inv_drive */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, start_ts_discharge, NULL, NULL, NULL, NULL, NULL },
    /* r2d               */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
};

/*  ____  _        _       
 * / ___|| |_ __ _| |_ ___ 
 * \___ \| __/ _` | __/ _ \
 *  ___) | || (_| | ||  __/
 * |____/ \__\__,_|\__\___|
 *                         
 *   __                  _   _                 
 *  / _|_   _ _ __   ___| |_(_) ___  _ __  ___ 
 * | |_| | | | '_ \ / __| __| |/ _ \| '_ \/ __|
 * |  _| |_| | | | | (__| |_| | (_) | | | \__ \
 * |_|  \__,_|_| |_|\___|\__|_|\___/|_| |_|___/
 */

// Function to be executed in state init
// valid return states: STATE_FATAL, STATE_IDLE
state_t do_init(state_data_t *data) {
    state_t next_state = STATE_FATAL;
    /* Your Code Here */

    switch (next_state) {
        case STATE_FATAL:
        case STATE_IDLE:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state fatal
// valid return states: NO_CHANGE, STATE_FATAL
state_t do_fatal(state_data_t *data) {
    state_t next_state = NO_CHANGE;
    /* Your Code Here */

    switch (next_state) {
        case NO_CHANGE:
        case STATE_FATAL:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state idle
// valid return states: NO_CHANGE, STATE_FLASH, STATE_PAUSE, STATE_FATAL, STATE_IDLE, STATE_WAIT_TS_PRECHARGE
state_t do_idle(state_data_t *data) {
    state_t next_state = NO_CHANGE;
    /* Your Code Here */

    switch (next_state) {
        case NO_CHANGE:
        case STATE_FLASH:
        case STATE_PAUSE:
        case STATE_FATAL:
        case STATE_IDLE:
        case STATE_WAIT_TS_PRECHARGE:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state flash
// valid return states: NO_CHANGE, STATE_FLASH, STATE_IDLE
state_t do_flash(state_data_t *data) {
    state_t next_state = NO_CHANGE;
    /* Your Code Here */

    switch (next_state) {
        case NO_CHANGE:
        case STATE_FLASH:
        case STATE_IDLE:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state pause
// valid return states: NO_CHANGE, STATE_PAUSE, STATE_IDLE
state_t do_pause(state_data_t *data) {
    state_t next_state = NO_CHANGE;
    /* Your Code Here */

    switch (next_state) {
        case NO_CHANGE:
        case STATE_PAUSE:
        case STATE_IDLE:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state wait_ts_precharge
// valid return states: NO_CHANGE, STATE_WAIT_TS_PRECHARGE, STATE_WAIT_DRIVER, STATE_WAIT_TS_DISCHARGE
state_t do_wait_ts_precharge(state_data_t *data) {
    state_t next_state = NO_CHANGE;
    /* Your Code Here */

    switch (next_state) {
        case NO_CHANGE:
        case STATE_WAIT_TS_PRECHARGE:
        case STATE_WAIT_DRIVER:
        case STATE_WAIT_TS_DISCHARGE:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state wait_driver
// valid return states: NO_CHANGE, STATE_WAIT_DRIVER, STATE_ENABLE_AS_DRIVER, STATE_ENABLE_INV_DRIVE, STATE_WAIT_TS_DISCHARGE
state_t do_wait_driver(state_data_t *data) {
    state_t next_state = NO_CHANGE;
    /* Your Code Here */

    switch (next_state) {
        case NO_CHANGE:
        case STATE_WAIT_DRIVER:
        case STATE_ENABLE_AS_DRIVER:
        case STATE_ENABLE_INV_DRIVE:
        case STATE_WAIT_TS_DISCHARGE:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state wait_ts_discharge
// valid return states: NO_CHANGE, STATE_IDLE, STATE_WAIT_TS_DISCHARGE
state_t do_wait_ts_discharge(state_data_t *data) {
    state_t next_state = NO_CHANGE;
    /* Your Code Here */

    switch (next_state) {
        case NO_CHANGE:
        case STATE_IDLE:
        case STATE_WAIT_TS_DISCHARGE:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state enable_as_driver
// valid return states: NO_CHANGE, STATE_ENABLE_AS_DRIVER, STATE_ENABLE_INV_DRIVE, STATE_WAIT_TS_DISCHARGE
state_t do_enable_as_driver(state_data_t *data) {
    state_t next_state = NO_CHANGE;
    /* Your Code Here */

    switch (next_state) {
        case NO_CHANGE:
        case STATE_ENABLE_AS_DRIVER:
        case STATE_ENABLE_INV_DRIVE:
        case STATE_WAIT_TS_DISCHARGE:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state enable_inv_drive
// valid return states: NO_CHANGE, STATE_ENABLE_INV_DRIVE, STATE_DISABLE_INV_DRIVE, STATE_R2D
state_t do_enable_inv_drive(state_data_t *data) {
    state_t next_state = NO_CHANGE;
    /* Your Code Here */

    switch (next_state) {
        case NO_CHANGE:
        case STATE_ENABLE_INV_DRIVE:
        case STATE_DISABLE_INV_DRIVE:
        case STATE_R2D:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state disable_as_driver
// valid return states: NO_CHANGE, STATE_DISABLE_AS_DRIVER, STATE_DISABLE_INV_DRIVE
state_t do_disable_as_driver(state_data_t *data) {
    state_t next_state = NO_CHANGE;
    /* Your Code Here */

    switch (next_state) {
        case NO_CHANGE:
        case STATE_DISABLE_AS_DRIVER:
        case STATE_DISABLE_INV_DRIVE:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state disable_inv_drive
// valid return states: NO_CHANGE, STATE_DISABLE_INV_DRIVE, STATE_WAIT_TS_DISCHARGE
state_t do_disable_inv_drive(state_data_t *data) {
    state_t next_state = NO_CHANGE;
    /* Your Code Here */

    switch (next_state) {
        case NO_CHANGE:
        case STATE_DISABLE_INV_DRIVE:
        case STATE_WAIT_TS_DISCHARGE:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state r2d
// valid return states: NO_CHANGE, STATE_DISABLE_AS_DRIVER, STATE_DISABLE_INV_DRIVE, STATE_R2D
state_t do_r2d(state_data_t *data) {
    state_t next_state = NO_CHANGE;
    /* Your Code Here */

    switch (next_state) {
        case NO_CHANGE:
        case STATE_DISABLE_AS_DRIVER:
        case STATE_DISABLE_INV_DRIVE:
        case STATE_R2D:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

/*  _____                    _ _   _              
 * |_   _| __ __ _ _ __  ___(_) |_(_) ___  _ __   
 *   | || '__/ _` | '_ \/ __| | __| |/ _ \| '_ \
 *   | || | | (_| | | | \__ \ | |_| | (_) | | | | 
 *   |_||_|  \__,_|_| |_|___/_|\__|_|\___/|_| |_| 
 *                                                
 *   __                  _   _                 
 *  / _|_   _ _ __   ___| |_(_) ___  _ __  ___ 
 * | |_| | | | '_ \ / __| __| |/ _ \| '_ \/ __|
 * |  _| |_| | | | | (__| |_| | (_) | | | \__ \
 * |_|  \__,_|_| |_|\___|\__|_|\___/|_| |_|___/
 */

// This function is called in 1 transition:
// 1. from idle to wait_ts_precharge
void start_ts_precharge(state_data_t *data) {
    /* Your Code Here */
}

// This function is called in 4 transitions:
// 1. from wait_ts_precharge to wait_ts_discharge
// 2. from wait_driver to wait_ts_discharge
// 3. from enable_as_driver to wait_ts_discharge
// 4. from disable_inv_drive to wait_ts_discharge
void start_ts_discharge(state_data_t *data) {
    /* Your Code Here */
}

/*  ____  _        _        
 * / ___|| |_ __ _| |_ ___  
 * \___ \| __/ _` | __/ _ \
 *  ___) | || (_| | ||  __/ 
 * |____/ \__\__,_|\__\___| 
 *                          
 *                                              
 *  _ __ ___   __ _ _ __   __ _  __ _  ___ _ __ 
 * | '_ ` _ \ / _` | '_ \ / _` |/ _` |/ _ \ '__|
 * | | | | | | (_| | | | | (_| | (_| |  __/ |   
 * |_| |_| |_|\__,_|_| |_|\__,_|\__, |\___|_|   
 *                              |___/           
 */

state_t run_state(state_t cur_state, state_data_t *data) {
    state_t new_state = state_table[cur_state](data);
    if (new_state == NO_CHANGE)
        new_state = cur_state;

    transition_func_t *transition = transition_table[cur_state][new_state];
    if (transition)
        transition(data);

    return new_state;
};

#ifdef TEST_MAIN
#include <unistd.h>
int main() {
    state_t cur_state = STATE_INIT;

    do {
        cur_state = run_state(cur_state, NULL);
        sleep(1);

    } while (1);

    return 0;
}
#endif
