/******************************************************************************
Finite State Machine
Project: ecu-fsm.dot
Description: ecu_fsm

Generated by gv_fsm ruby gem, see https://rubygems.org/gems/gv_fsm
gv_fsm version 0.5.2
Generation date: 2026-05-28 16:02:52 +0200
Generated from: ecu-fsm.dot
The finite state machine has:
  25 states
  4 transition functions

******************************************************************************/

#include "ecu_fsm.h"

// SEARCH FOR Your Code Here FOR CODE INSERTION POINTS!

EAGLETRT_STATIC void prv_periodically_send(enum CanPrimaryEcufsmVehiclestatus vehicle_status, enum CanPrimaryEcufsmKrakenstatus kraken_status, uint32_t tick) {
    identity_api_periodically_send_state(vehicle_status, kraken_status, tick);
    identity_api_periodically_send_version(tick);
    identity_api_periodically_send_libcan_version(tick);
    temperatures_api_periodically_send_temperatures(tick);
}

EAGLETRT_STATIC void prv_drain_can_tx_buffers(void) {
    can_communication_api_process_tx(CAN_COMMUNICATION_NETWORK_PRIMARY);
    can_communication_api_process_tx(CAN_COMMUNICATION_NETWORK_SECONDARY);
    can_communication_api_process_tx(CAN_COMMUNICATION_NETWORK_INVERTER);
}

EAGLETRT_STATIC void prv_drain_can_rx_buffers(void) {
    can_communication_api_process_rx(CAN_COMMUNICATION_NETWORK_PRIMARY);
    can_communication_api_process_rx(CAN_COMMUNICATION_NETWORK_SECONDARY);
    can_communication_api_process_rx(CAN_COMMUNICATION_NETWORK_INVERTER);
}

// GLOBALS
// State human-readable names
const char *state_names[] = { "init", "fatal", "idle", "flash", "pause", "manual_wait_ts_precharge", "as_off", "wait_driver", "manual_wait_ts_discharge", "manual_wait_inv_enable", "driving", "manual_wait_inv_disable", "as_off_wait_ts_precharge", "as_ready", "as_ready_wait_inv_enable", "as_emergency", "as_r2d", "as_driving", "as_finished", "as_off_wait_ts_discharge", "as_ready_wait_inv_disable", "as_finished_wait_inv_disable", "as_finished_wait_ts_discharge", "as_emergency_wait_inv_disable", "as_emergency_wait_ts_discharge" };

// List of state functions
state_func_t *const state_table[NUM_STATES] = {
    do_init,                           // in state init
    do_fatal,                          // in state fatal
    do_idle,                           // in state idle
    do_flash,                          // in state flash
    do_pause,                          // in state pause
    do_manual_wait_ts_precharge,       // in state manual_wait_ts_precharge
    do_as_off,                         // in state as_off
    do_wait_driver,                    // in state wait_driver
    do_manual_wait_ts_discharge,       // in state manual_wait_ts_discharge
    do_manual_wait_inv_enable,         // in state manual_wait_inv_enable
    do_driving,                        // in state driving
    do_manual_wait_inv_disable,        // in state manual_wait_inv_disable
    do_as_off_wait_ts_precharge,       // in state as_off_wait_ts_precharge
    do_as_ready,                       // in state as_ready
    do_as_ready_wait_inv_enable,       // in state as_ready_wait_inv_enable
    do_as_emergency,                   // in state as_emergency
    do_as_r2d,                         // in state as_r2d
    do_as_driving,                     // in state as_driving
    do_as_finished,                    // in state as_finished
    do_as_off_wait_ts_discharge,       // in state as_off_wait_ts_discharge
    do_as_ready_wait_inv_disable,      // in state as_ready_wait_inv_disable
    do_as_finished_wait_inv_disable,   // in state as_finished_wait_inv_disable
    do_as_finished_wait_ts_discharge,  // in state as_finished_wait_ts_discharge
    do_as_emergency_wait_inv_disable,  // in state as_emergency_wait_inv_disable
    do_as_emergency_wait_ts_discharge, // in state as_emergency_wait_ts_discharge
};

// Table of transition functions
transition_func_t *const transition_table[NUM_STATES][NUM_STATES] = {
    /* states:                            init              , fatal             , idle              , flash             , pause             , manual_wait_ts_precharge, as_off            , wait_driver       , manual_wait_ts_discharge, manual_wait_inv_enable, driving           , manual_wait_inv_disable, as_off_wait_ts_precharge, as_ready          , as_ready_wait_inv_enable, as_emergency      , as_r2d            , as_driving        , as_finished       , as_off_wait_ts_discharge, as_ready_wait_inv_disable, as_finished_wait_inv_disable, as_finished_wait_ts_discharge, as_emergency_wait_inv_disable, as_emergency_wait_ts_discharge */
    /* init                           */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* fatal                          */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* idle                           */ { NULL, NULL, NULL, NULL, NULL, start_ts_precharge, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* flash                          */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* pause                          */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* manual_wait_ts_precharge       */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, start_ts_discharge, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* as_off                         */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, start_ts_precharge, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* wait_driver                    */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, start_ts_discharge, start_inv_enable, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* manual_wait_ts_discharge       */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* manual_wait_inv_enable         */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, start_inv_disable, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* driving                        */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, start_inv_disable, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* manual_wait_inv_disable        */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, start_ts_discharge, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* as_off_wait_ts_precharge       */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, start_ts_discharge, NULL, NULL, NULL, NULL, NULL },
    /* as_ready                       */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, start_inv_enable, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* as_ready_wait_inv_enable       */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, start_inv_disable, NULL, NULL, NULL, NULL },
    /* as_emergency                   */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, start_inv_disable, NULL },
    /* as_r2d                         */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* as_driving                     */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* as_finished                    */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, start_inv_disable, NULL, NULL, NULL },
    /* as_off_wait_ts_discharge       */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* as_ready_wait_inv_disable      */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* as_finished_wait_inv_disable   */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, start_ts_discharge, NULL, NULL },
    /* as_finished_wait_ts_discharge  */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* as_emergency_wait_inv_disable  */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, start_ts_discharge },
    /* as_emergency_wait_ts_discharge */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
};

/*  ____  _        _       
 * / ___|| |_ __ _| |_ ___ 
 * \___ \| __/ _` | __/ _ \
 *  ___) | || (_| | ||  __/
 * |____/ \__\__,_|\__\___|
 *                         
 *   __                  _   _                 
 *  / _|_   _ _ __   ___| |_(_) ___  _ __  ___ 
 * | |_| | | | '_ \ / __| __| |/ _ \| '_ \/ __|
 * |  _| |_| | | | | (__| |_| | (_) | | | \__ \
 * |_|  \__,_|_| |_|\___|\__|_|\___/|_| |_|___/
 */

// Function to be executed in state init
// valid return states: STATE_FATAL, STATE_IDLE
state_t do_init(state_data_t *data) {
    state_t next_state = STATE_IDLE;
    /* Your Code Here */
    logger_api_log(LOGGER_LEVEL_INFO, "FSM: INIT state");

    // convert state data into POST struct configuration
    struct PostConfig *post_configuration = (struct PostConfig *)data;

    // NOLINTNEXTLINE(bugprone-branch-clone)
    if (post_api_do_init(post_configuration) != POST_RC_OK) {
        // Error during POST initialization
        logger_api_log(LOGGER_LEVEL_ERROR, "FSM: POST failed. Going to FATAL");
        next_state = STATE_FATAL;
    } else {
        buzzer_api_set_frequency(BUZZER_TYPE_ASSI, 1000);
        buzzer_api_set_amplitude(BUZZER_TYPE_ASSI, 0.33f);
        buzzer_api_set_duration(BUZZER_TYPE_ASSI, 800);
        buzzer_api_play_sync(BUZZER_TYPE_ASSI);
    }

    identity_api_send_state(CAN_PRIMARY_ECUFSM_VEHICLESTATUS_INIT, CAN_PRIMARY_ECUFSM_KRAKENSTATUS_INIT);

    // If ok, transit to idle

    switch (next_state) {
        case STATE_FATAL:
        case STATE_IDLE:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state fatal
// valid return states: NO_CHANGE, STATE_FATAL
state_t do_fatal(state_data_t *data) {
    state_t next_state = NO_CHANGE;
    /* Your Code Here */
    EAGLETRT_API_UNUSED(data);

    // fatal state is a sink, no other operation should be made
    logger_api_log(LOGGER_LEVEL_ERROR, "FSM: FATAL state");

    switch (next_state) {
        case NO_CHANGE:
        case STATE_FATAL:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state idle
// valid return states: NO_CHANGE, STATE_FLASH, STATE_PAUSE, STATE_FATAL, STATE_IDLE, STATE_MANUAL_WAIT_TS_PRECHARGE, STATE_AS_OFF
state_t do_idle(state_data_t *data) {
    state_t next_state = NO_CHANGE;
    /* Your Code Here */
    constexpr uint32_t tson_required_press_time = 2000;
    EAGLETRT_STATIC uint32_t tson_first_press_tick = 0;

    logger_api_log(LOGGER_LEVEL_INFO, "FSM: IDLE state");

    if (data == NULL) {
        logger_api_log(LOGGER_LEVEL_ERROR, "FSM: State data is NULL. Going to FATAL");
        return STATE_FATAL;
    }
    struct FsmData fsm_data = *(struct FsmData *)data;

    prv_drain_can_rx_buffers();

    switch (inverters_api_step(fsm_data.tick)) {
        case INVERTERS_RC_OK:
            break;
        case INVERTERS_RC_TX_ERROR:
            logger_api_log(LOGGER_LEVEL_ERROR, "Inverter TX error");
            break;
        default:
            logger_api_log(LOGGER_LEVEL_ERROR, "Inverter error");
            break;
    }

    // this logic does:
    // 1. If the TS ON button is pressed and this is the first time it is pressed, record the current tick.
    // 2. If the TS ON button is released, reset the recorded tick to 0.
    // 3. If the TS ON button has been pressed for more than 2 seconds, check if the voltage is lower than 60V. If it is, transition to the PRECHARGE state. If not, log an error and transition to the FATAL state
    if (vehicle_api_get_ts_on_button_pressed() && tson_first_press_tick == 0) {
        tson_first_press_tick = fsm_data.tick;
    } else if (!vehicle_api_get_ts_on_button_pressed()) {
        tson_first_press_tick = 0;
    } else if (fsm_data.tick - tson_first_press_tick > tson_required_press_time) {
        // NOLINTNEXTLINE(bugprone-branch-clone)
        if (tsac_api_is_tsac_status_timeout()) {
            logger_api_log(LOGGER_LEVEL_ERROR, "FSM: Aborting Precharge. TSAC status timeout!");
            shutdown_api_control_relay(false);
            next_state = STATE_MANUAL_WAIT_TS_DISCHARGE;
        } else if (!tsac_api_get_voltage_higher_than_60v()) {
            logger_api_log(LOGGER_LEVEL_INFO, "FSM: TS ON requested. Moving to PRECHARGE.");
            shutdown_api_control_relay(true);
            next_state = STATE_MANUAL_WAIT_TS_PRECHARGE;
        } else {
            logger_api_log(LOGGER_LEVEL_ERROR, "FSM: Aborting Precharge. DC Link already >60V!");
            next_state = STATE_FATAL;
        }
        tson_first_press_tick = 0;
    }

    tsac_api_periodically_require_tsac_status();
    prv_periodically_send(CAN_PRIMARY_ECUFSM_VEHICLESTATUS_IDLE, CAN_PRIMARY_ECUFSM_KRAKENSTATUS_IDLE, fsm_data.tick);

    prv_drain_can_tx_buffers();

    switch (next_state) {
        case NO_CHANGE:
        case STATE_FLASH:
        case STATE_PAUSE:
        case STATE_FATAL:
        case STATE_IDLE:
        case STATE_MANUAL_WAIT_TS_PRECHARGE:
        case STATE_AS_OFF:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state flash
// valid return states: NO_CHANGE, STATE_FLASH, STATE_IDLE
state_t do_flash(state_data_t *data) {
    // No CAN frame is defined for the flash state
    // for the moment it is left disabled
    state_t next_state = STATE_IDLE;
    /* Your Code Here */
    EAGLETRT_API_UNUSED(data);
    logger_api_log(LOGGER_LEVEL_INFO, "FSM: FLASH state");

    // Remain in flash until an external request is received
    // to indicate that flashing is aborted/terminated
    prv_drain_can_rx_buffers();

    switch (next_state) {
        case NO_CHANGE:
        case STATE_FLASH:
        case STATE_IDLE:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state pause
// valid return states: NO_CHANGE, STATE_PAUSE, STATE_IDLE
state_t do_pause(state_data_t *data) {
    // Pause won't be used during the 2026 season
    // For this reason, hard-code the fallback to STATE_IDLE
    state_t next_state = STATE_IDLE;
    /* Your Code Here */
    EAGLETRT_API_UNUSED(data);
    logger_api_log(LOGGER_LEVEL_INFO, "FSM: PAUSE state");

    switch (next_state) {
        case NO_CHANGE:
        case STATE_PAUSE:
        case STATE_IDLE:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state manual_wait_ts_precharge
// valid return states: NO_CHANGE, STATE_MANUAL_WAIT_TS_PRECHARGE, STATE_WAIT_DRIVER, STATE_MANUAL_WAIT_TS_DISCHARGE
state_t do_manual_wait_ts_precharge(state_data_t *data) {
    state_t next_state = NO_CHANGE;
    /* Your Code Here */
    logger_api_log(LOGGER_LEVEL_INFO, "FSM: MANUAL WAIT TS PRECHARGE state");

    if (data == NULL) {
        logger_api_log(LOGGER_LEVEL_ERROR, "FSM: State data is NULL. Going to FATAL");
        return STATE_FATAL;
    }
    struct FsmData fsm_data = *(struct FsmData *)data;

    prv_drain_can_rx_buffers();

    switch (inverters_api_step(fsm_data.tick)) {
        case INVERTERS_RC_OK:
            break;
        case INVERTERS_RC_TX_ERROR:
            logger_api_log(LOGGER_LEVEL_ERROR, "Inverter TX error");
            break;
        default:
            logger_api_log(LOGGER_LEVEL_ERROR, "Inverter error");
            break;
    }

    // NOLINTNEXTLINE(bugprone-branch-clone)
    if (tsac_api_is_tsac_status_timeout()) {
        logger_api_log(LOGGER_LEVEL_ERROR, "FSM: Precharge failed. TSAC status timeout!");
        shutdown_api_control_relay(false);
        next_state = STATE_MANUAL_WAIT_TS_DISCHARGE;
    } else if (shutdown_api_get_state(SHUTDOWN_NAME_AFTER_ECU) != SHUTDOWN_STATE_CLOSED) {
        logger_api_log(LOGGER_LEVEL_ERROR, "FSM: Aborting Precharge. Shutdown is open!");
        next_state = STATE_MANUAL_WAIT_TS_DISCHARGE;
    } else if (tsac_api_get_tsac_status() == CAN_PRIMARY_TSACSTATUS_MAINBOARDSTATUS_TS_ON && tsac_api_get_voltage_higher_than_60v()) {
        logger_api_log(LOGGER_LEVEL_INFO, "FSM: Precharge completed. Moving to WAIT_DRIVER.");
        next_state = STATE_WAIT_DRIVER;
    } else if (tsac_api_get_tsac_status() == CAN_PRIMARY_TSACSTATUS_MAINBOARDSTATUS_ERROR) {
        logger_api_log(LOGGER_LEVEL_ERROR, "FSM: Precharge failed. TSAC reported error!");
        next_state = STATE_MANUAL_WAIT_TS_DISCHARGE;
    }

    tsac_api_periodically_require_tsac_status();
    prv_periodically_send(CAN_PRIMARY_ECUFSM_VEHICLESTATUS_PRECHARGE, CAN_PRIMARY_ECUFSM_KRAKENSTATUS_MANUAL_WAIT_TS_PRECHARGE, fsm_data.tick);

    prv_drain_can_tx_buffers();

    switch (next_state) {
        case NO_CHANGE:
        case STATE_MANUAL_WAIT_TS_PRECHARGE:
        case STATE_WAIT_DRIVER:
        case STATE_MANUAL_WAIT_TS_DISCHARGE:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state as_off
// valid return states: NO_CHANGE, STATE_FATAL, STATE_IDLE, STATE_AS_OFF, STATE_AS_OFF_WAIT_TS_PRECHARGE
state_t do_as_off(state_data_t *data) {
    state_t next_state = NO_CHANGE;
    /* Your Code Here */
    EAGLETRT_API_UNUSED(data);

    switch (next_state) {
        case NO_CHANGE:
        case STATE_FATAL:
        case STATE_IDLE:
        case STATE_AS_OFF:
        case STATE_AS_OFF_WAIT_TS_PRECHARGE:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state wait_driver
// valid return states: NO_CHANGE, STATE_WAIT_DRIVER, STATE_MANUAL_WAIT_INV_ENABLE, STATE_MANUAL_WAIT_TS_DISCHARGE
state_t do_wait_driver(state_data_t *data) {
    state_t next_state = NO_CHANGE;
    /* Your Code Here */

    constexpr uint32_t tson_required_press_time = 2000;
    EAGLETRT_STATIC uint32_t tson_first_press_tick = 0;

    logger_api_log(LOGGER_LEVEL_INFO, "FSM: WAIT DRIVER state");

    if (data == NULL) {
        logger_api_log(LOGGER_LEVEL_ERROR, "FSM: State data is NULL. Going to FATAL");
        return STATE_FATAL;
    }
    struct FsmData fsm_data = *(struct FsmData *)data;

    prv_drain_can_rx_buffers();

    switch (inverters_api_step(fsm_data.tick)) {
        case INVERTERS_RC_OK:
            break;
        case INVERTERS_RC_TX_ERROR:
            logger_api_log(LOGGER_LEVEL_ERROR, "Inverter TX error");
            break;
        default:
            logger_api_log(LOGGER_LEVEL_ERROR, "Inverter error");
            break;
    }

    // This logic does:
    // 1. If the TS ON button is pressed and this is the first time it is pressed, record the current tick.
    // 2. If the TS ON button is released, reset the recorded tick to 0.
    // 3. If the TS ON button has been pressed for more than 2 seconds and the pedal has also been pressed for that time, transition to the INV ENABLE state.
    // 4. If the TS ON button has been pressed even once without the pedal, transition to the TS DISCHARGE state.
    // NOLINTNEXTLINE(bugprone-branch-clone)
    if (tsac_api_is_tsac_status_timeout()) {
        logger_api_log(LOGGER_LEVEL_ERROR, "FSM: TSAC status timeout!");
        shutdown_api_control_relay(false);
        next_state = STATE_MANUAL_WAIT_TS_DISCHARGE;
    } else if (tsac_api_get_tsac_status() != CAN_PRIMARY_TSACSTATUS_MAINBOARDSTATUS_TS_ON) {
        logger_api_log(LOGGER_LEVEL_ERROR, "FSM: TSAC not in TSON!");
        next_state = STATE_MANUAL_WAIT_TS_DISCHARGE;
    } else if (vehicle_api_get_ts_on_button_pressed() && !pedals_api_is_brake_pressed()) {
        logger_api_log(LOGGER_LEVEL_ERROR, "FSM: TS ON pressed without pedal. Moving to TS DISCHARGE.");
        next_state = STATE_MANUAL_WAIT_TS_DISCHARGE;
    } else if (vehicle_api_get_ts_on_button_pressed() && tson_first_press_tick == 0) {
        tson_first_press_tick = fsm_data.tick;
    } else if (!vehicle_api_get_ts_on_button_pressed()) {
        tson_first_press_tick = 0;
    } else if (fsm_data.tick - tson_first_press_tick > tson_required_press_time && pedals_api_is_brake_pressed()) {
        logger_api_log(LOGGER_LEVEL_INFO, "FSM: TS ON and pedal pressed. Moving to INV ENABLE.");
        next_state = STATE_MANUAL_WAIT_INV_ENABLE;
    }

    if (next_state != NO_CHANGE) {
        tson_first_press_tick = 0;
    }

    prv_periodically_send(CAN_PRIMARY_ECUFSM_VEHICLESTATUS_TSON, CAN_PRIMARY_ECUFSM_KRAKENSTATUS_WAIT_DRIVER, fsm_data.tick);
    tsac_api_periodically_require_tsac_status();
    prv_drain_can_tx_buffers();

    switch (next_state) {
        case NO_CHANGE:
        case STATE_WAIT_DRIVER:
        case STATE_MANUAL_WAIT_INV_ENABLE:
        case STATE_MANUAL_WAIT_TS_DISCHARGE:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state manual_wait_ts_discharge
// valid return states: NO_CHANGE, STATE_IDLE, STATE_MANUAL_WAIT_TS_DISCHARGE
state_t do_manual_wait_ts_discharge(state_data_t *data) {
    state_t next_state = NO_CHANGE;
    /* Your Code Here */

    logger_api_log(LOGGER_LEVEL_INFO, "FSM: WAIT TS DISCHARGE state");

    if (data == NULL) {
        logger_api_log(LOGGER_LEVEL_ERROR, "FSM: State data is NULL. Going to FATAL");
        return STATE_FATAL;
    }
    struct FsmData fsm_data = *(struct FsmData *)data;

    prv_drain_can_rx_buffers();

    switch (inverters_api_step(fsm_data.tick)) {
        case INVERTERS_RC_OK:
            break;
        case INVERTERS_RC_TX_ERROR:
            logger_api_log(LOGGER_LEVEL_ERROR, "Inverter TX error");
            break;
        default:
            logger_api_log(LOGGER_LEVEL_ERROR, "Inverter error");
            break;
    }

    // NOLINTNEXTLINE(bugprone-branch-clone)
    if (!tsac_api_get_voltage_higher_than_60v() || !tsac_api_is_tsac_status_timeout()) {
        logger_api_log(LOGGER_LEVEL_INFO, "FSM: TS DISCHARGE completed. Moving to IDLE.");
        next_state = STATE_IDLE;
    } else if (tsac_api_is_tsac_status_timeout()) {
        logger_api_log(LOGGER_LEVEL_ERROR, "FSM: TS DISCHARGE failed. TSAC status timeout!");
        shutdown_api_control_relay(false);
        next_state = STATE_IDLE;
    }

    if (tsac_api_is_tsac_status_timeout()) {
        shutdown_api_control_relay(false);
    }

    prv_periodically_send(CAN_PRIMARY_ECUFSM_VEHICLESTATUS_DISCHARGE, CAN_PRIMARY_ECUFSM_KRAKENSTATUS_MANUAL_WAIT_TS_DISCHARGE, fsm_data.tick);
    tsac_api_periodically_require_tsac_status();
    prv_drain_can_tx_buffers();

    switch (next_state) {
        case NO_CHANGE:
        case STATE_IDLE:
        case STATE_MANUAL_WAIT_TS_DISCHARGE:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state manual_wait_inv_enable
// valid return states: NO_CHANGE, STATE_MANUAL_WAIT_INV_ENABLE, STATE_DRIVING, STATE_MANUAL_WAIT_INV_DISABLE
state_t do_manual_wait_inv_enable(state_data_t *data) {
    state_t next_state = NO_CHANGE;
    /* Your Code Here */

    constexpr uint32_t buzzer_required_play_time = 2000;
    EAGLETRT_STATIC uint32_t buzzer_played_tick = 0;

    logger_api_log(LOGGER_LEVEL_INFO, "FSM: MANUAL WAIT INV ENABLE state");

    if (data == NULL) {
        logger_api_log(LOGGER_LEVEL_ERROR, "FSM: State data is NULL. Going to FATAL");
        return STATE_FATAL;
    }
    struct FsmData fsm_data = *(struct FsmData *)data;

    prv_drain_can_rx_buffers();

    switch (inverters_api_step(fsm_data.tick)) {
        case INVERTERS_RC_OK:
            break;
        case INVERTERS_RC_TX_ERROR:
            logger_api_log(LOGGER_LEVEL_ERROR, "Inverter TX error");
            break;
        default:
            logger_api_log(LOGGER_LEVEL_ERROR, "Inverter error");
            break;
    }

    inverters_api_arm(EPHORUS_WHEEL_FRONT_LEFT);
    inverters_api_arm(EPHORUS_WHEEL_FRONT_RIGHT);
    inverters_api_arm(EPHORUS_WHEEL_REAR_LEFT);
    inverters_api_arm(EPHORUS_WHEEL_REAR_RIGHT);

    // Logic is:
    // 1. If all inverters are in drive and the buzzer has not been played yet, play the buzzer and record the current tick.
    // 2. If all inverters are in drive and the buzzer has been played and the required play time has passed, transition to the DRIVING state.
    // 3. If not all inverters are in drive and the buzzer has been played, reset the buzzer played tick and transition to the MANUAL WAIT INV DISABLE state.
    if (tsac_api_get_tsac_status() != CAN_PRIMARY_TSACSTATUS_MAINBOARDSTATUS_TS_ON) {
        logger_api_log(LOGGER_LEVEL_ERROR, "FSM: TSAC not in TSON!");
        next_state = STATE_MANUAL_WAIT_INV_DISABLE;
    } else if (tsac_api_is_tsac_status_timeout()) {
        logger_api_log(LOGGER_LEVEL_ERROR, "FSM: TSAC status timeout!");
        shutdown_api_control_relay(false);
        next_state = STATE_MANUAL_WAIT_INV_DISABLE;
    } else if (inverters_api_is_all_in_drive() && buzzer_played_tick == 0) {
        buzzer_api_set_duration(BUZZER_TYPE_R2D, buzzer_required_play_time);
        buzzer_api_play_async(BUZZER_TYPE_R2D);
        buzzer_played_tick = fsm_data.tick;
    } else if (inverters_api_is_all_in_drive() && (fsm_data.tick - buzzer_played_tick) > buzzer_required_play_time) {
        logger_api_log(LOGGER_LEVEL_INFO, "FSM: INV ENABLE completed. Moving to DRIVING.");
        next_state = STATE_DRIVING;
    } else if (!inverters_api_is_all_in_drive() && buzzer_played_tick != 0) {
        buzzer_played_tick = 0;
        next_state = STATE_MANUAL_WAIT_INV_DISABLE;
    }

    if (next_state != NO_CHANGE) {
        buzzer_api_reset(BUZZER_TYPE_R2D);
        buzzer_played_tick = 0;
    }

    prv_periodically_send(CAN_PRIMARY_ECUFSM_VEHICLESTATUS_TSON, CAN_PRIMARY_ECUFSM_KRAKENSTATUS_MANUAL_WAIT_INV_ENABLE, fsm_data.tick);
    tsac_api_periodically_require_tsac_status();
    prv_drain_can_tx_buffers();

    switch (next_state) {
        case NO_CHANGE:
        case STATE_MANUAL_WAIT_INV_ENABLE:
        case STATE_DRIVING:
        case STATE_MANUAL_WAIT_INV_DISABLE:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state driving
// valid return states: NO_CHANGE, STATE_DRIVING, STATE_MANUAL_WAIT_INV_DISABLE
state_t do_driving(state_data_t *data) {
    state_t next_state = NO_CHANGE;
    /* Your Code Here */

    logger_api_log(LOGGER_LEVEL_INFO, "FSM: DRIVING state");

    if (data == NULL) {
        logger_api_log(LOGGER_LEVEL_ERROR, "FSM: State data is NULL. Going to FATAL");
        return STATE_FATAL;
    }
    struct FsmData fsm_data = *(struct FsmData *)data;

    prv_drain_can_rx_buffers();

    switch (inverters_api_step(fsm_data.tick)) {
        case INVERTERS_RC_OK:
            break;
        case INVERTERS_RC_TX_ERROR:
            logger_api_log(LOGGER_LEVEL_ERROR, "Inverter TX error");
            break;
        default:
            logger_api_log(LOGGER_LEVEL_ERROR, "Inverter error");
            break;
    }

    // Logic is:
    // 1. If the TS ON button is pressed, transition to the MANUAL WAIT INV DISABLE state.
    // 2. If not all inverters are in drive, log an error and transition to the MANUAL WAIT INV DISABLE state.
    // 3. If the TSAC is not in TSON, log an error and transition to the MANUAL WAIT INV DISABLE state.
    // 4. If the pedals have timed out, log an error and transition to the MANUAL WAIT INV DISABLE state.
    // 5. If all conditions are met, get the requested torque from the pedals and set it for all inverters.
    // NOLINTNEXTLINE(bugprone-branch-clone)
    if (vehicle_api_get_ts_on_button_pressed()) {
        next_state = STATE_MANUAL_WAIT_INV_DISABLE;
    } else if (!inverters_api_is_all_in_drive()) {
        logger_api_log(LOGGER_LEVEL_ERROR, "FSM: Not all inverters in drive!");
        next_state = STATE_MANUAL_WAIT_INV_DISABLE;
    } else if (tsac_api_is_tsac_status_timeout()) {
        logger_api_log(LOGGER_LEVEL_ERROR, "FSM: TSAC status timeout!");
        shutdown_api_control_relay(false);
        next_state = STATE_MANUAL_WAIT_INV_DISABLE;
    } else if (tsac_api_get_tsac_status() != CAN_PRIMARY_TSACSTATUS_MAINBOARDSTATUS_TS_ON) {
        logger_api_log(LOGGER_LEVEL_ERROR, "FSM: TSAC not in TSON!");
        next_state = STATE_MANUAL_WAIT_INV_DISABLE;
    } else if (pedals_api_is_timeout()) {
        logger_api_log(LOGGER_LEVEL_ERROR, "FSM: Pedal timeout!");
        next_state = STATE_MANUAL_WAIT_INV_DISABLE;
    } else if (shutdown_api_get_state(SHUTDOWN_NAME_AFTER_ECU) != SHUTDOWN_STATE_CLOSED) {
        logger_api_log(LOGGER_LEVEL_ERROR, "FSM: Shutdown is open!");
        next_state = STATE_MANUAL_WAIT_INV_DISABLE;
    } else {
        float requested_torque = pedals_api_get_requested_throttle_torque();
        inverters_api_set_torque(EPHORUS_WHEEL_REAR_LEFT, requested_torque);
        inverters_api_set_torque(EPHORUS_WHEEL_REAR_RIGHT, requested_torque);
        inverters_api_set_torque(EPHORUS_WHEEL_FRONT_LEFT, requested_torque);
        inverters_api_set_torque(EPHORUS_WHEEL_FRONT_RIGHT, requested_torque);
    }

    prv_periodically_send(CAN_PRIMARY_ECUFSM_VEHICLESTATUS_R2D, CAN_PRIMARY_ECUFSM_KRAKENSTATUS_DRIVING, fsm_data.tick);
    tsac_api_periodically_require_tsac_status();
    prv_drain_can_tx_buffers();

    switch (next_state) {
        case NO_CHANGE:
        case STATE_DRIVING:
        case STATE_MANUAL_WAIT_INV_DISABLE:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state manual_wait_inv_disable
// valid return states: NO_CHANGE, STATE_MANUAL_WAIT_INV_DISABLE, STATE_MANUAL_WAIT_TS_DISCHARGE
state_t do_manual_wait_inv_disable(state_data_t *data) {
    state_t next_state = NO_CHANGE;
    /* Your Code Here */

    logger_api_log(LOGGER_LEVEL_INFO, "FSM: MANUAL WAIT INV DISABLE state");

    if (data == NULL) {
        logger_api_log(LOGGER_LEVEL_ERROR, "FSM: State data is NULL. Going to FATAL");
        return STATE_FATAL;
    }
    struct FsmData fsm_data = *(struct FsmData *)data;

    prv_drain_can_rx_buffers();

    switch (inverters_api_step(fsm_data.tick)) {
        case INVERTERS_RC_OK:
            break;
        case INVERTERS_RC_TX_ERROR:
            logger_api_log(LOGGER_LEVEL_ERROR, "Inverter TX error");
            break;
        default:
            logger_api_log(LOGGER_LEVEL_ERROR, "Inverter error");
            break;
    }

    // NOLINTNEXTLINE(bugprone-branch-clone)
    if (!inverters_api_is_all_in_drive()) {
        logger_api_log(LOGGER_LEVEL_INFO, "FSM: INV DISABLE completed. Moving to TS DISCHARGE.");
        next_state = STATE_MANUAL_WAIT_TS_DISCHARGE;
    } else {
        inverters_api_disarm(EPHORUS_WHEEL_FRONT_LEFT);
        inverters_api_disarm(EPHORUS_WHEEL_FRONT_RIGHT);
        inverters_api_disarm(EPHORUS_WHEEL_REAR_LEFT);
        inverters_api_disarm(EPHORUS_WHEEL_REAR_RIGHT);
    }

    prv_periodically_send(CAN_PRIMARY_ECUFSM_VEHICLESTATUS_R2D, CAN_PRIMARY_ECUFSM_KRAKENSTATUS_DRIVING, fsm_data.tick);
    tsac_api_periodically_require_tsac_status();
    prv_drain_can_tx_buffers();

    switch (next_state) {
        case NO_CHANGE:
        case STATE_MANUAL_WAIT_INV_DISABLE:
        case STATE_MANUAL_WAIT_TS_DISCHARGE:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state as_off_wait_ts_precharge
// valid return states: NO_CHANGE, STATE_AS_READY, STATE_AS_OFF_WAIT_TS_PRECHARGE, STATE_AS_OFF_WAIT_TS_DISCHARGE
state_t do_as_off_wait_ts_precharge(state_data_t *data) {
    state_t next_state = NO_CHANGE;
    /* Your Code Here */
    EAGLETRT_API_UNUSED(data);

    switch (next_state) {
        case NO_CHANGE:
        case STATE_AS_READY:
        case STATE_AS_OFF_WAIT_TS_PRECHARGE:
        case STATE_AS_OFF_WAIT_TS_DISCHARGE:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state as_ready
// valid return states: NO_CHANGE, STATE_AS_READY, STATE_AS_READY_WAIT_INV_ENABLE, STATE_AS_EMERGENCY
state_t do_as_ready(state_data_t *data) {
    state_t next_state = NO_CHANGE;
    /* Your Code Here */
    EAGLETRT_API_UNUSED(data);

    switch (next_state) {
        case NO_CHANGE:
        case STATE_AS_READY:
        case STATE_AS_READY_WAIT_INV_ENABLE:
        case STATE_AS_EMERGENCY:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state as_ready_wait_inv_enable
// valid return states: NO_CHANGE, STATE_AS_R2D, STATE_AS_READY_WAIT_INV_ENABLE, STATE_AS_READY_WAIT_INV_DISABLE
state_t do_as_ready_wait_inv_enable(state_data_t *data) {
    state_t next_state = NO_CHANGE;
    /* Your Code Here */
    EAGLETRT_API_UNUSED(data);

    switch (next_state) {
        case NO_CHANGE:
        case STATE_AS_R2D:
        case STATE_AS_READY_WAIT_INV_ENABLE:
        case STATE_AS_READY_WAIT_INV_DISABLE:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state as_emergency
// valid return states: NO_CHANGE, STATE_AS_EMERGENCY, STATE_AS_EMERGENCY_WAIT_INV_DISABLE
state_t do_as_emergency(state_data_t *data) {
    state_t next_state = NO_CHANGE;
    /* Your Code Here */
    EAGLETRT_API_UNUSED(data);

    switch (next_state) {
        case NO_CHANGE:
        case STATE_AS_EMERGENCY:
        case STATE_AS_EMERGENCY_WAIT_INV_DISABLE:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state as_r2d
// valid return states: STATE_AS_DRIVING, STATE_AS_EMERGENCY
state_t do_as_r2d(state_data_t *data) {
    state_t next_state = STATE_AS_DRIVING;
    /* Your Code Here */
    EAGLETRT_API_UNUSED(data);

    switch (next_state) {
        case STATE_AS_DRIVING:
        case STATE_AS_EMERGENCY:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state as_driving
// valid return states: NO_CHANGE, STATE_AS_DRIVING, STATE_AS_FINISHED, STATE_AS_EMERGENCY
state_t do_as_driving(state_data_t *data) {
    state_t next_state = NO_CHANGE;
    /* Your Code Here */
    EAGLETRT_API_UNUSED(data);

    switch (next_state) {
        case NO_CHANGE:
        case STATE_AS_DRIVING:
        case STATE_AS_FINISHED:
        case STATE_AS_EMERGENCY:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state as_finished
// valid return states: NO_CHANGE, STATE_AS_FINISHED, STATE_AS_FINISHED_WAIT_INV_DISABLE
state_t do_as_finished(state_data_t *data) {
    state_t next_state = NO_CHANGE;
    /* Your Code Here */
    EAGLETRT_API_UNUSED(data);

    switch (next_state) {
        case NO_CHANGE:
        case STATE_AS_FINISHED:
        case STATE_AS_FINISHED_WAIT_INV_DISABLE:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state as_off_wait_ts_discharge
// valid return states: NO_CHANGE, STATE_AS_OFF, STATE_AS_OFF_WAIT_TS_DISCHARGE
state_t do_as_off_wait_ts_discharge(state_data_t *data) {
    state_t next_state = NO_CHANGE;
    /* Your Code Here */
    EAGLETRT_API_UNUSED(data);

    switch (next_state) {
        case NO_CHANGE:
        case STATE_AS_OFF:
        case STATE_AS_OFF_WAIT_TS_DISCHARGE:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state as_ready_wait_inv_disable
// valid return states: NO_CHANGE, STATE_AS_READY_WAIT_INV_DISABLE, STATE_AS_EMERGENCY
state_t do_as_ready_wait_inv_disable(state_data_t *data) {
    state_t next_state = NO_CHANGE;
    /* Your Code Here */
    EAGLETRT_API_UNUSED(data);

    switch (next_state) {
        case NO_CHANGE:
        case STATE_AS_READY_WAIT_INV_DISABLE:
        case STATE_AS_EMERGENCY:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state as_finished_wait_inv_disable
// valid return states: NO_CHANGE, STATE_AS_FINISHED_WAIT_INV_DISABLE, STATE_AS_FINISHED_WAIT_TS_DISCHARGE
state_t do_as_finished_wait_inv_disable(state_data_t *data) {
    state_t next_state = NO_CHANGE;
    /* Your Code Here */
    EAGLETRT_API_UNUSED(data);

    switch (next_state) {
        case NO_CHANGE:
        case STATE_AS_FINISHED_WAIT_INV_DISABLE:
        case STATE_AS_FINISHED_WAIT_TS_DISCHARGE:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state as_finished_wait_ts_discharge
// valid return states: NO_CHANGE, STATE_AS_FINISHED, STATE_AS_FINISHED_WAIT_TS_DISCHARGE
state_t do_as_finished_wait_ts_discharge(state_data_t *data) {
    state_t next_state = NO_CHANGE;
    /* Your Code Here */
    EAGLETRT_API_UNUSED(data);

    switch (next_state) {
        case NO_CHANGE:
        case STATE_AS_FINISHED:
        case STATE_AS_FINISHED_WAIT_TS_DISCHARGE:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state as_emergency_wait_inv_disable
// valid return states: NO_CHANGE, STATE_AS_EMERGENCY_WAIT_INV_DISABLE, STATE_AS_EMERGENCY_WAIT_TS_DISCHARGE
state_t do_as_emergency_wait_inv_disable(state_data_t *data) {
    state_t next_state = NO_CHANGE;
    /* Your Code Here */
    EAGLETRT_API_UNUSED(data);

    switch (next_state) {
        case NO_CHANGE:
        case STATE_AS_EMERGENCY_WAIT_INV_DISABLE:
        case STATE_AS_EMERGENCY_WAIT_TS_DISCHARGE:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state as_emergency_wait_ts_discharge
// valid return states: NO_CHANGE, STATE_AS_EMERGENCY, STATE_AS_EMERGENCY_WAIT_TS_DISCHARGE
state_t do_as_emergency_wait_ts_discharge(state_data_t *data) {
    state_t next_state = NO_CHANGE;
    /* Your Code Here */
    EAGLETRT_API_UNUSED(data);

    switch (next_state) {
        case NO_CHANGE:
        case STATE_AS_EMERGENCY:
        case STATE_AS_EMERGENCY_WAIT_TS_DISCHARGE:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

/*  _____                    _ _   _              
 * |_   _| __ __ _ _ __  ___(_) |_(_) ___  _ __   
 *   | || '__/ _` | '_ \/ __| | __| |/ _ \| '_ \
 *   | || | | (_| | | | \__ \ | |_| | (_) | | | | 
 *   |_||_|  \__,_|_| |_|___/_|\__|_|\___/|_| |_| 
 *                                                
 *   __                  _   _                 
 *  / _|_   _ _ __   ___| |_(_) ___  _ __  ___ 
 * | |_| | | | '_ \ / __| __| |/ _ \| '_ \/ __|
 * |  _| |_| | | | | (__| |_| | (_) | | | \__ \
 * |_|  \__,_|_| |_|\___|\__|_|\___/|_| |_|___/
 */

// This function is called in 2 transitions:
// 1. from idle to manual_wait_ts_precharge
// 2. from as_off to as_off_wait_ts_precharge
void start_ts_precharge(state_data_t *data) {
    /* Your Code Here */
    EAGLETRT_API_UNUSED(data);

    tsac_api_set_ts_state_to_require(true);
}

// This function is called in 6 transitions:
// 1. from manual_wait_ts_precharge to manual_wait_ts_discharge
// 2. from wait_driver to manual_wait_ts_discharge
// 3. from manual_wait_inv_disable to manual_wait_ts_discharge
// 4. from as_off_wait_ts_precharge to as_off_wait_ts_discharge
// 5. from as_finished_wait_inv_disable to as_finished_wait_ts_discharge
// 6. from as_emergency_wait_inv_disable to as_emergency_wait_ts_discharge
void start_ts_discharge(state_data_t *data) {
    /* Your Code Here */
    EAGLETRT_API_UNUSED(data);

    tsac_api_set_ts_state_to_require(false);
}

// This function is called in 2 transitions:
// 1. from wait_driver to manual_wait_inv_enable
// 2. from as_ready to as_ready_wait_inv_enable
void start_inv_enable(state_data_t *data) {
    /* Your Code Here */
    EAGLETRT_API_UNUSED(data);

    inverters_api_arm(EPHORUS_WHEEL_FRONT_LEFT);
    inverters_api_arm(EPHORUS_WHEEL_FRONT_RIGHT);
    inverters_api_arm(EPHORUS_WHEEL_REAR_LEFT);
    inverters_api_arm(EPHORUS_WHEEL_REAR_RIGHT);
}

// This function is called in 5 transitions:
// 1. from manual_wait_inv_enable to manual_wait_inv_disable
// 2. from driving to manual_wait_inv_disable
// 3. from as_ready_wait_inv_enable to as_ready_wait_inv_disable
// 4. from as_finished to as_finished_wait_inv_disable
// 5. from as_emergency to as_emergency_wait_inv_disable
void start_inv_disable(state_data_t *data) {
    /* Your Code Here */
    EAGLETRT_API_UNUSED(data);

    inverters_api_disarm(EPHORUS_WHEEL_FRONT_LEFT);
    inverters_api_disarm(EPHORUS_WHEEL_FRONT_RIGHT);
    inverters_api_disarm(EPHORUS_WHEEL_REAR_LEFT);
    inverters_api_disarm(EPHORUS_WHEEL_REAR_RIGHT);
}

/*  ____  _        _        
 * / ___|| |_ __ _| |_ ___  
 * \___ \| __/ _` | __/ _ \
 *  ___) | || (_| | ||  __/ 
 * |____/ \__\__,_|\__\___| 
 *                          
 *                                              
 *  _ __ ___   __ _ _ __   __ _  __ _  ___ _ __ 
 * | '_ ` _ \ / _` | '_ \ / _` |/ _` |/ _ \ '__|
 * | | | | | | (_| | | | | (_| | (_| |  __/ |   
 * |_| |_| |_|\__,_|_| |_|\__,_|\__, |\___|_|   
 *                              |___/           
 */

state_t run_state(state_t cur_state, state_data_t *data) {
    state_t new_state = state_table[cur_state](data);
    if (new_state == NO_CHANGE)
        new_state = cur_state;

    transition_func_t *transition = transition_table[cur_state][new_state];
    if (transition) {
        transition(data);
    }

    return new_state;
}

#ifdef TEST_MAIN
#include <unistd.h>
int main() {
    state_t cur_state = STATE_INIT;

    do {
        cur_state = run_state(cur_state, NULL);
        sleep(1);

    } while (1);

    return 0;
}
#endif
